<a href="https://colab.research.google.com/github/yakshdhankhar1810-oss/html-project/blob/main/RippleWatch_AI_V2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# STEP 1: Environment check

import sys
import os
from pathlib import Path

print("Python version:", sys.version)
print("Current directory:", os.getcwd())

PROJECT_DIR = Path("/content/ripplewatch_ai_v2")
PROJECT_DIR.mkdir(parents=True, exist_ok=True)

for folder in ["data", "logs", "backups"]:
    (PROJECT_DIR / folder).mkdir(exist_ok=True)

print("\nProject directory:", PROJECT_DIR)
print("Folders created:")

for path in sorted(PROJECT_DIR.iterdir()):
    print("-", path.name)

print("\nSTEP 1 PASSED")

Python version: 3.13.16 (main, Oct  1 2026, 15:40:24) [GCC 13.3.0]
Current directory: /content

Project directory: /content/ripplewatch_ai_v2
Folders created:
- backups
- data
- logs

STEP 1 PASSED

In [ ]:
# STEP 2: Install required libraries

%pip install -q pandas requests python-dateutil

In [ ]:
# Verify installations

import pandas as pd
import requests
from dateutil import parser

print("Pandas version:", pd.__version__)
print("Requests version:", requests.__version__)
print("Date parsing library: Ready")
print("\nSTEP 2 PASSED")

Pandas version: 2.2.3
Requests version: 2.32.4
Date parsing library: Ready

STEP 2 PASSED

In [ ]:
# STEP 3: Create initial project data

import pandas as pd
from pathlib import Path

PROJECT_DIR = Path("/content/ripplewatch_ai_v2")
DATA_DIR = PROJECT_DIR / "data"

# Supplier database
suppliers = pd.DataFrame([
    {
        "supplier_id": "S001",
        "supplier_name": "Alpha Components",
        "country": "Unknown",
        "criticality": "High"
    },
    {
        "supplier_id": "S002",
        "supplier_name": "Beta Electronics",
        "country": "Unknown",
        "criticality": "High"
    },
    {
        "supplier_id": "S003",
        "supplier_name": "Gamma Materials",
        "country": "Unknown",
        "criticality": "Medium"
    }
])

# Product database
products = pd.DataFrame([
    {
        "product_id": "P001",
        "product_name": "Smart Sensor",
        "supplier_id": "S001"
    },
    {
        "product_id": "P002",
        "product_name": "Control Board",
        "supplier_id": "S001"
    },
    {
        "product_id": "P003",
        "product_name": "Power Module",
        "supplier_id": "S002"
    },
    {
        "product_id": "P004",
        "product_name": "Industrial Monitor",
        "supplier_id": "S002"
    },
    {
        "product_id": "P005",
        "product_name": "Protective Casing",
        "supplier_id": "S003"
    }
])

# Save databases
suppliers.to_csv(DATA_DIR / "suppliers.csv", index=False)
products.to_csv(DATA_DIR / "products.csv", index=False)

print("Suppliers created:", len(suppliers))
print("Products created:", len(products))

print("\nSUPPLIER DATABASE")
display(suppliers)

print("\nPRODUCT DATABASE")
display(products)

print("\nSaved files:")
for file in sorted(DATA_DIR.glob("*.csv")):
    print("-", file.name)

print("\nSTEP 3 PASSED")

Suppliers created: 3
Products created: 5

SUPPLIER DATABASE

  supplier_id     supplier_name  country criticality
0        S001  Alpha Components  Unknown        High
1        S002  Beta Electronics  Unknown        High
2        S003   Gamma Materials  Unknown      Medium

PRODUCT DATABASE

  product_id        product_name supplier_id
0       P001        Smart Sensor        S001
1       P002       Control Board        S001
2       P003        Power Module        S002
3       P004  Industrial Monitor        S002
4       P005   Protective Casing        S003

Saved files:
- products.csv
- suppliers.csv

STEP 3 PASSED

In [ ]:
# STEP 4: Create evidence database

import pandas as pd
from pathlib import Path

PROJECT_DIR = Path("/content/ripplewatch_ai_v2")
DATA_DIR = PROJECT_DIR / "data"

evidence_columns = [
    "evidence_id",
    "source_title",
    "source_url",
    "source_published_date",
    "fetched_at",
    "evidence_sentence",
    "event_type",
    "matched_supplier_names",
    "matched_product_names",
    "source_date_status",
    "review_status",
    "risk_score",
    "supplier_specific_alert_allowed"
]

evidence = pd.DataFrame(columns=evidence_columns)

evidence_file = DATA_DIR / "evidence.csv"
evidence.to_csv(evidence_file, index=False)

# Reload and verify the saved file
check = pd.read_csv(evidence_file)

print("Evidence columns:", len(check.columns))
print("Evidence records:", len(check))
print("\nColumns:")
for column in check.columns:
    print("-", column)

print("\nSaved to:", evidence_file)
print("\nSTEP 4 PASSED")

Evidence columns: 13
Evidence records: 0

Columns:
- evidence_id
- source_title
- source_url
- source_published_date
- fetched_at
- evidence_sentence
- event_type
- matched_supplier_names
- matched_product_names
- source_date_status
- review_status
- risk_score
- supplier_specific_alert_allowed

Saved to: /content/ripplewatch_ai_v2/data/evidence.csv

STEP 4 PASSED

In [ ]:
# STEP 5A: Securely load TinyFish API key

import os
from getpass import getpass

TINYFISH_API_KEY = getpass("Enter your TinyFish API key: ").strip()

if not TINYFISH_API_KEY:
    raise ValueError("API key is empty. Please run this cell again.")

os.environ["TINYFISH_API_KEY"] = TINYFISH_API_KEY

print("API key loaded.")
print("Key value hidden for security.")
print("STEP 5A PASSED")

Enter your TinyFish API key: ··········
API key loaded.
Key value hidden for security.
STEP 5A PASSED

In [ ]:
import os
import requests

API_KEY = os.environ.get("TINYFISH_API_KEY")

if not API_KEY:
    raise ValueError("API key missing. Run Step 5A again.")

response = requests.post(
    "https://api.fetch.tinyfish.ai",
    headers={
        "X-API-Key": API_KEY,
        "Content-Type": "application/json"
    },
    json={
        "urls": ["https://example.com"],
        "format": "markdown"
    },
    timeout=120
)

print("HTTP status:", response.status_code)

if response.ok:
    print("STEP 5B PASSED — request accepted!")
    try:
        data = response.json()
        print("Response keys:", list(data.keys()))
        print("Response preview:", str(data)[:700])
    except ValueError:
        print("Response received; format was not JSON.")
else:
    print("API error:", response.text[:500])

HTTP status: 200
STEP 5B PASSED — request accepted!
Response keys: ['results', 'errors']
Response preview: {'results': [{'url': 'https://example.com', 'final_url': 'https://example.com', 'title': 'Example Domain', 'description': None, 'language': 'en', 'text': 'This domain is for use in documentation examples without needing permission. This is not a service; avoid relying on it for testing and monitoring purposes.', 'author': None, 'published_date': None, 'latency_ms': 36.23453299951507, 'format': 'markdown'}], 'errors': []}

In [ ]:
# STEP 6: Build reusable TinyFish fetcher

import os
import requests
from datetime import datetime, timezone

TINYFISH_ENDPOINT = "https://api.fetch.tinyfish.ai"


def fetch_article(url):
    """Fetch one article using TinyFish."""

    api_key = os.environ.get("TINYFISH_API_KEY")

    if not api_key:
        raise ValueError(
            "TinyFish API key missing. Run Step 5A first."
        )

    response = requests.post(
        TINYFISH_ENDPOINT,
        headers={
            "X-API-Key": api_key,
            "Content-Type": "application/json"
        },
        json={
            "urls": [url],
            "format": "markdown"
        },
        timeout=120
    )

    response.raise_for_status()
    payload = response.json()

    results = payload.get("results", [])
    errors = payload.get("errors", [])

    if not results:
        return {
            "requested_url": url,
            "title": None,
            "final_url": None,
            "text": "",
            "published_date": None,
            "fetched_at": datetime.now(timezone.utc).isoformat(),
            "status": "fetch_failed",
            "error": str(errors)[:500]
        }

    article = results[0]
    article_text = article.get("text") or ""

    return {
        "requested_url": url,
        "title": article.get("title"),
        "final_url": article.get("final_url"),
        "text": article_text,
        "published_date": article.get("published_date"),
        "fetched_at": datetime.now(timezone.utc).isoformat(),
        "status": "fetched" if article_text.strip() else "empty_content",
        "error": ""
    }


# Test with a harmless example page
test_article = fetch_article("https://example.com")

print("Status:", test_article["status"])
print("Title:", test_article["title"])
print("Final URL:", test_article["final_url"])
print("Text length:", len(test_article["text"]))
print("Published date:", test_article["published_date"])
print("\nSTEP 6 PASSED" if test_article["status"] == "fetched"
      else "STEP 6 NEEDS REVIEW")

Status: fetched
Title: Example Domain
Final URL: https://example.com
Text length: 156
Published date: None

STEP 6 PASSED

In [ ]:
# STEP 7: Fetch candidate supply-chain articles

import pandas as pd
from pathlib import Path

PROJECT_DIR = Path("/content/ripplewatch_ai_v2")
DATA_DIR = PROJECT_DIR / "data"

candidate_urls = [
    "https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/",
    "https://example.com/"
]

fetched_articles = []

for url in candidate_urls:
    print("\nFetching:", url)

    try:
        article = fetch_article(url)
        fetched_articles.append(article)

        print("Status:", article["status"])
        print("Title:", article["title"])
        print("Text length:", len(article["text"]))
        print("Published date:", article["published_date"])

    except Exception as exc:
        print("Fetch error:", str(exc)[:300])

# Save raw fetched results for inspection
raw_file = DATA_DIR / "raw_articles.csv"

raw_df = pd.DataFrame(fetched_articles)
raw_df.to_csv(raw_file, index=False)

print("\nArticles processed:", len(fetched_articles))
print("Saved to:", raw_file)
print("\nSTEP 7 COMPLETED — inspect results before using as evidence")

Fetching: https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/
Status: fetched
Title: Electronics manufacturers fret over extreme heat disruptions
Text length: 4511
Published date: 2026-09-22

Fetching: https://example.com/
Status: fetched
Title: Example Domain
Text length: 156
Published date: None

Articles processed: 2
Saved to: /content/ripplewatch_ai_v2/data/raw_articles.csv

STEP 7 COMPLETED — inspect results before using as evidence

In [ ]:
# STEP 8: Inspect the real article text

import pandas as pd
import re
from pathlib import Path

PROJECT_DIR = Path("/content/ripplewatch_ai_v2")
DATA_DIR = PROJECT_DIR / "data"

raw_df = pd.read_csv(DATA_DIR / "raw_articles.csv")

# Exclude the example test page
article_rows = raw_df[
    raw_df["requested_url"].astype(str).str.contains(
        "supplychaindive.com", case=False, na=False
    )
]

if article_rows.empty:
    raise ValueError("SupplyChainDive article not found in raw_articles.csv")

article = article_rows.iloc[0]
text = str(article.get("text", ""))

# Split article text into readable sentences
clean_text = re.sub(r"\s+", " ", text).strip()
sentences = re.split(r"(?<=[.!?])\s+(?=[A-Z0-9“\"'])", clean_text)

# Keep substantive sentences, not very short fragments
sentences = [
    sentence.strip()
    for sentence in sentences
    if len(sentence.strip()) >= 40
]

print("Article:", article.get("title"))
print("Published date:", article.get("published_date"))
print("Extracted sentence candidates:", len(sentences))
print("\n--- FIRST 15 SENTENCE CANDIDATES ---\n")

for i, sentence in enumerate(sentences[:15], start=1):
    print(f"{i}. {sentence}\n")

# Save candidates for later review
candidates_df = pd.DataFrame({
    "candidate_id": [f"E{i:03d}" for i in range(1, len(sentences) + 1)],
    "source_title": article.get("title"),
    "source_url": article.get("final_url"),
    "source_published_date": article.get("published_date"),
    "evidence_sentence": sentences,
    "review_status": "pending_review"
})

candidates_df.to_csv(
    DATA_DIR / "evidence_candidates.csv",
    index=False
)

print("Saved candidates:", DATA_DIR / "evidence_candidates.csv")
print("\nSTEP 8 COMPLETED — candidates require review")

Article: Electronics manufacturers fret over extreme heat disruptions
Published date: 2026-09-22
Extracted sentence candidates: 26

--- FIRST 15 SENTENCE CANDIDATES ---

1. An article from # Electronics manufacturers fret over extreme heat disruptions High temperatures are delaying supplier deliveries and hobbling productivity in the process, per the Global Electronics Association.

2. 22, 2026 Antone Gonsalves Reporter A sign reading “Extreme Heat Danger” warns Death Valley National Park visitors during a heat wave impacting much of California on July 9, 2024.

3. A Global Electronics Association survey found that two-fifths of manufacturers globally reported extreme heat-related supply chain disruptions in 2026.

4. Mario Tama via Getty Images This audio is auto-generated.

5. Please let us know if you have feedback.

6. Electronics manufacturers worldwide reported extreme heat-related supply chain disruptions this year, with supplier delivery delays cited as the most severe impacts, an industry trade association survey released Tuesday found.

7. Almost half of manufacturers surveyed by the Global Electronics Association said supplier fulfillment was most affected, with 50% of manufacturers in North America, Europe and Asia Pacific reporting disruptions.

8. The survey did not ask for the exact types of supplier delays.

9. However, Chief Economist Shawn DuBravac told Supply Chain Dive there were likely multiple causes, such as labor issues, supplier factory constraints and freight and warehouse bottlenecks.

10. “My sense is that it was probably an assortment of different things that would fall under that broader category of supplier delays,” DuBravac said.

11. Two-fifths of manufacturers globally reported some type of heat-related supply chain disruption.

12. In North America, minor or no disruptions were most common, at 20% and 57% of respondents, respectively, while moderate and major interruptions were each cited by 6%. #### North American electronic supply chains face extreme heat-related impacts The percentage of specific disruptions faced by electronics manufacturers in the region who reported impacts from extreme heat on their operations in 2026.

13. More than four-fifths of manufacturers worldwide who experienced heat-related disruptions reported negative impacts on productivity and operational throughput, per the survey.

14. In North America, 13% reported major impacts, and 50% reported moderate impacts.

15. “To me, a moderate impact would be something that has to be addressed, something that impacted throughput, that impacted production schedules,” DuBravac said.

Saved candidates: /content/ripplewatch_ai_v2/data/evidence_candidates.csv

STEP 8 COMPLETED — candidates require review

In [ ]:
# STEP 9: Filter relevant evidence candidates for review

import pandas as pd
from pathlib import Path

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")

candidates = pd.read_csv(DATA_DIR / "evidence_candidates.csv")

keywords = [
    "supply chain",
    "supplier",
    "delivery",
    "disruption",
    "extreme heat",
    "productivity",
    "operational throughput",
    "factory",
    "freight",
    "warehouse",
    "manufacturing"
]

def find_relevant_keywords(sentence):
    text = str(sentence).lower()
    return [word for word in keywords if word in text]

candidates["relevant_keywords"] = candidates[
    "evidence_sentence"
].apply(find_relevant_keywords)

review_queue = candidates[
    candidates["relevant_keywords"].apply(len) > 0
].copy()

review_queue["review_status"] = "pending_review"
review_queue["evidence_type"] = "industry_signal"
review_queue["supplier_specific_alert_allowed"] = False

review_queue.to_csv(
    DATA_DIR / "evidence_review_queue.csv",
    index=False
)

print("Total candidates:", len(candidates))
print("Candidates sent for review:", len(review_queue))
print("\n--- REVIEW QUEUE ---\n")

for _, row in review_queue.iterrows():
    print(f'{row["candidate_id"]}: {row["evidence_sentence"]}')
    print("Keywords:", ", ".join(row["relevant_keywords"]))
    print()

print("Saved to:", DATA_DIR / "evidence_review_queue.csv")
print("\nSTEP 9 PASSED")

Total candidates: 26
Candidates sent for review: 18

--- REVIEW QUEUE ---

E001: An article from # Electronics manufacturers fret over extreme heat disruptions High temperatures are delaying supplier deliveries and hobbling productivity in the process, per the Global Electronics Association.
Keywords: supplier, disruption, extreme heat, productivity

E002: 22, 2026 Antone Gonsalves Reporter A sign reading “Extreme Heat Danger” warns Death Valley National Park visitors during a heat wave impacting much of California on July 9, 2024.
Keywords: extreme heat

E003: A Global Electronics Association survey found that two-fifths of manufacturers globally reported extreme heat-related supply chain disruptions in 2026.
Keywords: supply chain, disruption, extreme heat

E006: Electronics manufacturers worldwide reported extreme heat-related supply chain disruptions this year, with supplier delivery delays cited as the most severe impacts, an industry trade association survey released Tuesday found.
Keywords: supply chain, supplier, delivery, disruption, extreme heat

E007: Almost half of manufacturers surveyed by the Global Electronics Association said supplier fulfillment was most affected, with 50% of manufacturers in North America, Europe and Asia Pacific reporting disruptions.
Keywords: supplier, disruption

E008: The survey did not ask for the exact types of supplier delays.
Keywords: supplier

E009: However, Chief Economist Shawn DuBravac told Supply Chain Dive there were likely multiple causes, such as labor issues, supplier factory constraints and freight and warehouse bottlenecks.
Keywords: supply chain, supplier, factory, freight, warehouse

E010: “My sense is that it was probably an assortment of different things that would fall under that broader category of supplier delays,” DuBravac said.
Keywords: supplier

E011: Two-fifths of manufacturers globally reported some type of heat-related supply chain disruption.
Keywords: supply chain, disruption

E012: In North America, minor or no disruptions were most common, at 20% and 57% of respondents, respectively, while moderate and major interruptions were each cited by 6%. #### North American electronic supply chains face extreme heat-related impacts The percentage of specific disruptions faced by electronics manufacturers in the region who reported impacts from extreme heat on their operations in 2026.
Keywords: supply chain, disruption, extreme heat

E013: More than four-fifths of manufacturers worldwide who experienced heat-related disruptions reported negative impacts on productivity and operational throughput, per the survey.
Keywords: disruption, productivity, operational throughput

E016: North American firms that had not experienced heat-related disruptions are still anxious about potential issues.The most cited anticipated bottlenecks were operating constraints, including cooling limits, and power reliability issues, including curtailments, at 29% each, the survey found.
Keywords: disruption

E017: Other potential disruptions included transportation delays, unplanned equipment downtime and supplier delivery delays, with 17% of North American firms citing these.
Keywords: supplier, delivery, disruption

E018: Single-digit percentages cited customer demand disruptions, missed shifts, reduced staffing and product quality defects.
Keywords: disruption

E019: More than half of manufacturers globally said their supply chains were exposed to severe heat-related disruptions.
Keywords: supply chain, disruption

E021: Looking ahead, more than two-thirds of manufacturers worldwide expected extreme heat-driven interruptions in productivity or operational throughput in the coming years, the survey found.
Keywords: extreme heat, productivity, operational throughput

E023: Subscribe to the Supply Chain Dive free daily newsletter Overall, the survey showed that contingency planning for heat-related supply chain disruptions was essential, DuBravac said.
Keywords: supply chain, disruption

E026: Sign up here.* * Add us on Google * + Copy link + Email + LinkedIn + X/Twitter + Facebook + Print + License Filed Under: Risk and Resilience, Operations Management, Procurement, Logistics, Manufacturing
Keywords: manufacturing

Saved to: /content/ripplewatch_ai_v2/data/evidence_review_queue.csv

STEP 9 PASSED

In [ ]:

# STEP 10: Clean the evidence review queue

import pandas as pd
from pathlib import Path

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")

queue = pd.read_csv(DATA_DIR / "evidence_review_queue.csv")

# Remove obvious page clutter and irrelevant text
exclude_phrases = [
    "subscribe to",
    "sign up here",
    "add us on google",
    "copy link",
    "email",
    "linkedin",
    "facebook",
    "filed under:",
    "this audio is auto-generated",
    "please let us know if you have feedback",
    "via getty images",
    "a sign reading"
]

def is_useful_evidence(sentence):
    text = str(sentence).lower()

    if any(phrase in text for phrase in exclude_phrases):
        return False

    # Keep sentences that express an event, impact,
    # observed disruption, or a potential risk.
    evidence_terms = [
        "reported", "disruption", "disruptions",
        "delays", "delayed", "affected", "impact",
        "impacts", "bottlenecks", "constraints",
        "interruptions", "exposed", "expected",
        "anticipated", "throughput", "fulfillment"
    ]

    return any(term in text for term in evidence_terms)

queue["keep_for_review"] = queue["evidence_sentence"].apply(
    is_useful_evidence
)

clean_queue = queue[queue["keep_for_review"]].copy()

clean_queue["review_status"] = "pending_review"
clean_queue["evidence_type"] = "industry_signal"
clean_queue["supplier_specific_alert_allowed"] = False

output_path = DATA_DIR / "evidence_clean_queue.csv"
clean_queue.to_csv(output_path, index=False)

print("Original review queue:", len(queue))
print("Kept for evidence review:", len(clean_queue))
print("Removed as likely page clutter:", len(queue) - len(clean_queue))

print("\n--- CLEAN EVIDENCE QUEUE ---\n")

for _, row in clean_queue.iterrows():
    print(f'{row["candidate_id"]}: {row["evidence_sentence"]}\n')

print("Saved to:", output_path)
print("\nSTEP 10 PASSED")

Original review queue: 18
Kept for evidence review: 15
Removed as likely page clutter: 3

--- CLEAN EVIDENCE QUEUE ---

E001: An article from # Electronics manufacturers fret over extreme heat disruptions High temperatures are delaying supplier deliveries and hobbling productivity in the process, per the Global Electronics Association.

E003: A Global Electronics Association survey found that two-fifths of manufacturers globally reported extreme heat-related supply chain disruptions in 2026.

E006: Electronics manufacturers worldwide reported extreme heat-related supply chain disruptions this year, with supplier delivery delays cited as the most severe impacts, an industry trade association survey released Tuesday found.

E007: Almost half of manufacturers surveyed by the Global Electronics Association said supplier fulfillment was most affected, with 50% of manufacturers in North America, Europe and Asia Pacific reporting disruptions.

E008: The survey did not ask for the exact types of supplier delays.

E009: However, Chief Economist Shawn DuBravac told Supply Chain Dive there were likely multiple causes, such as labor issues, supplier factory constraints and freight and warehouse bottlenecks.

E010: “My sense is that it was probably an assortment of different things that would fall under that broader category of supplier delays,” DuBravac said.

E011: Two-fifths of manufacturers globally reported some type of heat-related supply chain disruption.

E012: In North America, minor or no disruptions were most common, at 20% and 57% of respondents, respectively, while moderate and major interruptions were each cited by 6%. #### North American electronic supply chains face extreme heat-related impacts The percentage of specific disruptions faced by electronics manufacturers in the region who reported impacts from extreme heat on their operations in 2026.

E013: More than four-fifths of manufacturers worldwide who experienced heat-related disruptions reported negative impacts on productivity and operational throughput, per the survey.

E016: North American firms that had not experienced heat-related disruptions are still anxious about potential issues.The most cited anticipated bottlenecks were operating constraints, including cooling limits, and power reliability issues, including curtailments, at 29% each, the survey found.

E017: Other potential disruptions included transportation delays, unplanned equipment downtime and supplier delivery delays, with 17% of North American firms citing these.

E018: Single-digit percentages cited customer demand disruptions, missed shifts, reduced staffing and product quality defects.

E019: More than half of manufacturers globally said their supply chains were exposed to severe heat-related disruptions.

E021: Looking ahead, more than two-thirds of manufacturers worldwide expected extreme heat-driven interruptions in productivity or operational throughput in the coming years, the survey found.

Saved to: /content/ripplewatch_ai_v2/data/evidence_clean_queue.csv

STEP 10 PASSED

In [ ]:

# STEP 11: Classify evidence signals

import pandas as pd
from pathlib import Path

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")

queue = pd.read_csv(DATA_DIR / "evidence_clean_queue.csv")

def classify_evidence(sentence):
    text = str(sentence).lower()

    future_terms = [
        "looking ahead",
        "in the coming years",
        "expected",
        "anticipated",
        "potential disruptions",
        "still anxious",
        "had not experienced"
    ]

    limitation_terms = [
        "did not ask",
        "my sense",
        "likely multiple causes"
    ]

    if any(term in text for term in future_terms):
        return "potential_future_risk"

    if any(term in text for term in limitation_terms):
        return "context_or_uncertainty"

    if any(term in text for term in [
        "reported", "disruptions", "delays",
        "affected", "negative impacts", "exposed"
    ]):
        return "reported_industry_signal"

    return "needs_manual_review"


queue["signal_class"] = queue["evidence_sentence"].apply(
    classify_evidence
)

# Keep the alert permission disabled for all industry-level evidence
queue["supplier_specific_alert_allowed"] = False

output_path = DATA_DIR / "evidence_classified.csv"
queue.to_csv(output_path, index=False)

print("--- CLASSIFICATION COUNTS ---")
print(queue["signal_class"].value_counts().to_string())

print("\n--- CLASSIFIED EVIDENCE ---\n")
for _, row in queue.iterrows():
    print(f'{row["candidate_id"]} | {row["signal_class"]}')
    print(row["evidence_sentence"])
    print()

print("Supplier-specific alerts allowed:",
      queue["supplier_specific_alert_allowed"].sum())
print("Saved to:", output_path)
print("\nSTEP 11 PASSED")

--- CLASSIFICATION COUNTS ---
signal_class
reported_industry_signal    9
context_or_uncertainty      3
potential_future_risk       3

--- CLASSIFIED EVIDENCE ---

E001 | reported_industry_signal
An article from # Electronics manufacturers fret over extreme heat disruptions High temperatures are delaying supplier deliveries and hobbling productivity in the process, per the Global Electronics Association.

E003 | reported_industry_signal
A Global Electronics Association survey found that two-fifths of manufacturers globally reported extreme heat-related supply chain disruptions in 2026.

E006 | reported_industry_signal
Electronics manufacturers worldwide reported extreme heat-related supply chain disruptions this year, with supplier delivery delays cited as the most severe impacts, an industry trade association survey released Tuesday found.

E007 | reported_industry_signal
Almost half of manufacturers surveyed by the Global Electronics Association said supplier fulfillment was most affected, with 50% of manufacturers in North America, Europe and Asia Pacific reporting disruptions.

E008 | context_or_uncertainty
The survey did not ask for the exact types of supplier delays.

E009 | context_or_uncertainty
However, Chief Economist Shawn DuBravac told Supply Chain Dive there were likely multiple causes, such as labor issues, supplier factory constraints and freight and warehouse bottlenecks.

E010 | context_or_uncertainty
“My sense is that it was probably an assortment of different things that would fall under that broader category of supplier delays,” DuBravac said.

E011 | reported_industry_signal
Two-fifths of manufacturers globally reported some type of heat-related supply chain disruption.

E012 | reported_industry_signal
In North America, minor or no disruptions were most common, at 20% and 57% of respondents, respectively, while moderate and major interruptions were each cited by 6%. #### North American electronic supply chains face extreme heat-related impacts The percentage of specific disruptions faced by electronics manufacturers in the region who reported impacts from extreme heat on their operations in 2026.

E013 | reported_industry_signal
More than four-fifths of manufacturers worldwide who experienced heat-related disruptions reported negative impacts on productivity and operational throughput, per the survey.

E016 | potential_future_risk
North American firms that had not experienced heat-related disruptions are still anxious about potential issues.The most cited anticipated bottlenecks were operating constraints, including cooling limits, and power reliability issues, including curtailments, at 29% each, the survey found.

E017 | potential_future_risk
Other potential disruptions included transportation delays, unplanned equipment downtime and supplier delivery delays, with 17% of North American firms citing these.

E018 | reported_industry_signal
Single-digit percentages cited customer demand disruptions, missed shifts, reduced staffing and product quality defects.

E019 | reported_industry_signal
More than half of manufacturers globally said their supply chains were exposed to severe heat-related disruptions.

E021 | potential_future_risk
Looking ahead, more than two-thirds of manufacturers worldwide expected extreme heat-driven interruptions in productivity or operational throughput in the coming years, the survey found.

Supplier-specific alerts allowed: 0
Saved to: /content/ripplewatch_ai_v2/data/evidence_classified.csv

STEP 11 PASSED

In [ ]:

# STEP 12: Normalize evidence and flag duplicates

import pandas as pd
import re
from pathlib import Path

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")

df = pd.read_csv(DATA_DIR / "evidence_classified.csv")

def normalize_evidence(sentence):
    text = str(sentence)

    # Remove Markdown heading markers
    text = re.sub(r"#{1,6}\s*", "", text)

    # Remove common article-title prefix when present
    text = re.sub(
        r"^An article from\s+Electronics manufacturers fret over extreme heat disruptions\s*",
        "",
        text,
        flags=re.IGNORECASE
    )

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

df["clean_evidence_sentence"] = df["evidence_sentence"].apply(
    normalize_evidence
)

# Create normalized text key to identify exact/near-exact repeats
df["dedup_key"] = (
    df["clean_evidence_sentence"]
    .str.lower()
    .str.replace(r"[^a-z0-9]+", " ", regex=True)
    .str.strip()
)

df["duplicate_text"] = df.duplicated(
    subset=["dedup_key"],
    keep="first"
)

print("Total records:", len(df))
print("Duplicate-text records flagged:", int(df["duplicate_text"].sum()))

print("\n--- CLEANED EVIDENCE PREVIEW ---\n")
for _, row in df.iterrows():
    status = "DUPLICATE TEXT" if row["duplicate_text"] else "KEEP"
    print(f'{row["candidate_id"]} | {status}')
    print(row["clean_evidence_sentence"])
    print()

output_path = DATA_DIR / "evidence_normalized.csv"
df.to_csv(output_path, index=False)

print("Saved to:", output_path)
print("\nSTEP 12 PASSED")

Total records: 15
Duplicate-text records flagged: 0

--- CLEANED EVIDENCE PREVIEW ---

E001 | KEEP
High temperatures are delaying supplier deliveries and hobbling productivity in the process, per the Global Electronics Association.

E003 | KEEP
A Global Electronics Association survey found that two-fifths of manufacturers globally reported extreme heat-related supply chain disruptions in 2026.

E006 | KEEP
Electronics manufacturers worldwide reported extreme heat-related supply chain disruptions this year, with supplier delivery delays cited as the most severe impacts, an industry trade association survey released Tuesday found.

E007 | KEEP
Almost half of manufacturers surveyed by the Global Electronics Association said supplier fulfillment was most affected, with 50% of manufacturers in North America, Europe and Asia Pacific reporting disruptions.

E008 | KEEP
The survey did not ask for the exact types of supplier delays.

E009 | KEEP
However, Chief Economist Shawn DuBravac told Supply Chain Dive there were likely multiple causes, such as labor issues, supplier factory constraints and freight and warehouse bottlenecks.

E010 | KEEP
“My sense is that it was probably an assortment of different things that would fall under that broader category of supplier delays,” DuBravac said.

E011 | KEEP
Two-fifths of manufacturers globally reported some type of heat-related supply chain disruption.

E012 | KEEP
In North America, minor or no disruptions were most common, at 20% and 57% of respondents, respectively, while moderate and major interruptions were each cited by 6%. North American electronic supply chains face extreme heat-related impacts The percentage of specific disruptions faced by electronics manufacturers in the region who reported impacts from extreme heat on their operations in 2026.

E013 | KEEP
More than four-fifths of manufacturers worldwide who experienced heat-related disruptions reported negative impacts on productivity and operational throughput, per the survey.

E016 | KEEP
North American firms that had not experienced heat-related disruptions are still anxious about potential issues.The most cited anticipated bottlenecks were operating constraints, including cooling limits, and power reliability issues, including curtailments, at 29% each, the survey found.

E017 | KEEP
Other potential disruptions included transportation delays, unplanned equipment downtime and supplier delivery delays, with 17% of North American firms citing these.

E018 | KEEP
Single-digit percentages cited customer demand disruptions, missed shifts, reduced staffing and product quality defects.

E019 | KEEP
More than half of manufacturers globally said their supply chains were exposed to severe heat-related disruptions.

E021 | KEEP
Looking ahead, more than two-thirds of manufacturers worldwide expected extreme heat-driven interruptions in productivity or operational throughput in the coming years, the survey found.

Saved to: /content/ripplewatch_ai_v2/data/evidence_normalized.csv

STEP 12 PASSED

In [ ]:

# STEP 13: Validate source metadata and evidence quality

import pandas as pd
from pathlib import Path

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")

evidence = pd.read_csv(
    DATA_DIR / "evidence_normalized.csv"
)
articles = pd.read_csv(
    DATA_DIR / "raw_articles.csv"
)

print("Raw article columns:", articles.columns.tolist())
print("Evidence columns:", evidence.columns.tolist())

# Inspect article metadata before building final evidence records
print("\n--- SOURCE METADATA ---\n")

for _, article in articles.iterrows():
    print("Title:", article.get("title", ""))
    print("URL:", article.get("final_url", article.get("requested_url", "")))
    print("Published date:", article.get("published_date", ""))
    print("Fetch status:", article.get("status", ""))
    print()

# Basic quality checks
evidence["evidence_quality"] = "needs_review"

text = evidence["clean_evidence_sentence"].fillna("").str.strip()
evidence.loc[text.str.len() >= 40, "evidence_quality"] = "candidate"

evidence["supplier_specific_alert_allowed"] = False

print("--- EVIDENCE QUALITY COUNTS ---")
print(evidence["evidence_quality"].value_counts().to_string())

print("\nSupplier-specific alerts allowed:",
      int(evidence["supplier_specific_alert_allowed"].sum()))

print("\nSTEP 13 METADATA INSPECTION COMPLETE")

Raw article columns: ['requested_url', 'title', 'final_url', 'text', 'published_date', 'fetched_at', 'status', 'error']
Evidence columns: ['candidate_id', 'source_title', 'source_url', 'source_published_date', 'evidence_sentence', 'review_status', 'relevant_keywords', 'evidence_type', 'supplier_specific_alert_allowed', 'keep_for_review', 'signal_class', 'clean_evidence_sentence', 'dedup_key', 'duplicate_text']

--- SOURCE METADATA ---

Title: Electronics manufacturers fret over extreme heat disruptions
URL: https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/
Published date: 2026-09-22
Fetch status: fetched

Title: Example Domain
URL: https://example.com
Published date: nan
Fetch status: fetched

--- EVIDENCE QUALITY COUNTS ---
evidence_quality
candidate    15

Supplier-specific alerts allowed: 0

STEP 13 METADATA INSPECTION COMPLETE

In [ ]:

# STEP 14: Attach original source metadata

import pandas as pd
from pathlib import Path

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")

evidence = pd.read_csv(
    DATA_DIR / "evidence_normalized.csv"
)
articles = pd.read_csv(
    DATA_DIR / "raw_articles.csv"
)

# Build a source lookup using the original requested URL.
# The URL in evidence may be Markdown-formatted, so use
# the original article URL to identify the source.
articles["source_key"] = (
    articles["final_url"]
    .fillna(articles["requested_url"])
    .astype(str)
    .str.strip()
)

def clean_url(value):
    value = str(value).strip()

    # Convert Markdown links like [URL](URL) to plain URLs.
    if value.startswith("[") and "](" in value and value.endswith(")"):
        value = value[1:value.index("](")]

    return value

evidence["source_url_clean"] = evidence["source_url"].apply(clean_url)

# Match evidence to the article by URL, not by title alone.
source_lookup = articles.set_index("source_key").to_dict("index")

def get_source_metadata(url):
    article = source_lookup.get(url, {})
    return pd.Series({
        "verified_source_title": article.get("title"),
        "verified_source_url": article.get("final_url") or article.get("requested_url"),
        "verified_published_date": article.get("published_date"),
        "verified_fetch_status": article.get("status", "source_not_matched")
    })

metadata = evidence["source_url_clean"].apply(get_source_metadata)

evidence = pd.concat([evidence, metadata], axis=1)

# Keep the records review-only until evidence is validated.
evidence["supplier_specific_alert_allowed"] = False

output_path = DATA_DIR / "evidence_with_sources.csv"
evidence.to_csv(output_path, index=False)

print("Evidence records:", len(evidence))
print("Matched source records:",
      int(evidence["verified_source_title"].notna().sum()))
print("Unmatched source records:",
      int(evidence["verified_source_title"].isna().sum()))

print("\n--- SOURCE MATCH PREVIEW ---\n")
print(evidence[[
    "candidate_id",
    "verified_source_title",
    "verified_published_date",
    "verified_fetch_status"
]].to_string(index=False))

print("\nSupplier-specific alerts allowed:",
      int(evidence["supplier_specific_alert_allowed"].sum()))
print("Saved to:", output_path)
print("\nSTEP 14 COMPLETE")

Evidence records: 15
Matched source records: 15
Unmatched source records: 0

--- SOURCE MATCH PREVIEW ---

candidate_id                                        verified_source_title verified_published_date verified_fetch_status
        E001 Electronics manufacturers fret over extreme heat disruptions              2026-09-22               fetched
        E003 Electronics manufacturers fret over extreme heat disruptions              2026-09-22               fetched
        E006 Electronics manufacturers fret over extreme heat disruptions              2026-09-22               fetched
        E007 Electronics manufacturers fret over extreme heat disruptions              2026-09-22               fetched
        E008 Electronics manufacturers fret over extreme heat disruptions              2026-09-22               fetched
        E009 Electronics manufacturers fret over extreme heat disruptions              2026-09-22               fetched
        E010 Electronics manufacturers fret over extreme heat disruptions              2026-09-22               fetched
        E011 Electronics manufacturers fret over extreme heat disruptions              2026-09-22               fetched
        E012 Electronics manufacturers fret over extreme heat disruptions              2026-09-22               fetched
        E013 Electronics manufacturers fret over extreme heat disruptions              2026-09-22               fetched
        E016 Electronics manufacturers fret over extreme heat disruptions              2026-09-22               fetched
        E017 Electronics manufacturers fret over extreme heat disruptions              2026-09-22               fetched
        E018 Electronics manufacturers fret over extreme heat disruptions              2026-09-22               fetched
        E019 Electronics manufacturers fret over extreme heat disruptions              2026-09-22               fetched
        E021 Electronics manufacturers fret over extreme heat disruptions              2026-09-22               fetched

Supplier-specific alerts allowed: 0
Saved to: /content/ripplewatch_ai_v2/data/evidence_with_sources.csv

STEP 14 COMPLETE

In [ ]:

# STEP 15: Validate source dates and review eligibility

import pandas as pd
from pathlib import Path
from datetime import datetime, timezone

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")

df = pd.read_csv(DATA_DIR / "evidence_with_sources.csv")

today = datetime.now(timezone.utc).date()

def validate_date(value):
    if pd.isna(value) or not str(value).strip():
        return "MISSING_DATE"

    parsed = pd.to_datetime(value, errors="coerce", utc=True)

    if pd.isna(parsed):
        return "UNPARSEABLE"

    published = parsed.date()

    if published > today:
        return "FUTURE_DATE"

    age_days = (today - published).days

    if age_days <= 30:
        return "RECENT"
    elif age_days <= 90:
        return "OLDER"
    else:
        return "STALE"

df["source_date_status"] = df["verified_published_date"].apply(
    validate_date
)

def assign_review_status(row):
    if row["verified_fetch_status"] != "fetched":
        return "source_fetch_review"

    if row["source_date_status"] in [
        "MISSING_DATE", "UNPARSEABLE", "FUTURE_DATE"
    ]:
        return "date_review_required"

    return "manual_evidence_review"

df["review_status_final"] = df.apply(
    assign_review_status, axis=1
)

# Never enable supplier-specific alerts from industry-only evidence.
df["supplier_specific_alert_allowed"] = False

output_path = DATA_DIR / "evidence_date_review.csv"
df.to_csv(output_path, index=False)

print("--- DATE STATUS COUNTS ---")
print(df["source_date_status"].value_counts().to_string())

print("\n--- REVIEW STATUS COUNTS ---")
print(df["review_status_final"].value_counts().to_string())

print("\n--- RECORD PREVIEW ---")
print(df[[
    "candidate_id",
    "verified_published_date",
    "source_date_status",
    "review_status_final"
]].to_string(index=False))

print("\nSupplier-specific alerts allowed:",
      int(df["supplier_specific_alert_allowed"].sum()))

print("Saved to:", output_path)
print("\nSTEP 15 COMPLETE")

--- DATE STATUS COUNTS ---
source_date_status
OLDER    15

--- REVIEW STATUS COUNTS ---
review_status_final
manual_evidence_review    15

--- RECORD PREVIEW ---
candidate_id verified_published_date source_date_status    review_status_final
        E001              2026-09-22              OLDER manual_evidence_review
        E003              2026-09-22              OLDER manual_evidence_review
        E006              2026-09-22              OLDER manual_evidence_review
        E007              2026-09-22              OLDER manual_evidence_review
        E008              2026-09-22              OLDER manual_evidence_review
        E009              2026-09-22              OLDER manual_evidence_review
        E010              2026-09-22              OLDER manual_evidence_review
        E011              2026-09-22              OLDER manual_evidence_review
        E012              2026-09-22              OLDER manual_evidence_review
        E013              2026-09-22              OLDER manual_evidence_review
        E016              2026-09-22              OLDER manual_evidence_review
        E017              2026-09-22              OLDER manual_evidence_review
        E018              2026-09-22              OLDER manual_evidence_review
        E019              2026-09-22              OLDER manual_evidence_review
        E021              2026-09-22              OLDER manual_evidence_review

Supplier-specific alerts allowed: 0
Saved to: /content/ripplewatch_ai_v2/data/evidence_date_review.csv

STEP 15 COMPLETE

In [ ]:

import pandas as pd
from pathlib import Path

# STEP 16: INDUSTRY RISK SCORING

base_dir = Path("/content/ripplewatch_ai_v2/data")

input_path = base_dir / "evidence_date_review.csv"
output_path = base_dir / "industry_risk_scores.csv"

# 1. Load input data
if not input_path.exists():
    raise FileNotFoundError(
        f"Input file not found: {input_path}\n"
        "Please check whether the previous step completed successfully."
    )

df = pd.read_csv(input_path)

# 2. Remove duplicate column names, if any
df = df.loc[:, ~df.columns.duplicated()].copy()

# 3. Check required columns
required_columns = ["candidate_id", "signal_class"]

missing_columns = [
    col for col in required_columns if col not in df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}\n"
        f"Available columns: {df.columns.tolist()}"
    )

# 4. Calculate preliminary industry risk scores
scores = []
reasons_list = []

for _, row in df.iterrows():
    signal_class = str(row["signal_class"]).strip().lower()

    # Use existing reason labels if present; otherwise start empty
    reasons = []

    # Context-only records receive zero
    if signal_class == "context_or_uncertainty":
        score = 0
        reasons.append("context_only")

    else:
        score = 0

        # Apply the existing project signal classifications
        if signal_class == "reported_industry_signal":
            # Determine the reason from available text/labels
            text_parts = []

            for col in [
                "risk_reasons",
                "evidence_sentence",
                "source_title",
                "verified_source_title",
                "signal_type",
                "event_type",
            ]:
                if col in df.columns and pd.notna(row.get(col)):
                    text_parts.append(str(row[col]))

            text = " ".join(text_parts).lower()

            if any(term in text for term in [
                "supply chain", "supply-chain",
                "component shortage", "delivery delay",
                "disruption", "factory shutdown",
                "operational impact"
            ]):
                score += 25
                reasons.append("industry_supply_chain_signal")

            if any(term in text for term in [
                "operational impact", "production stopped",
                "shutdown", "delivery delay", "factory closure"
            ]):
                score += 15
                reasons.append("reported_operational_impact")

            if not reasons:
                reasons.append("general_industry_context")

        elif signal_class == "potential_future_risk":
            text_parts = []

            for col in [
                "risk_reasons",
                "evidence_sentence",
                "source_title",
                "verified_source_title",
                "signal_type",
                "event_type",
            ]:
                if col in df.columns and pd.notna(row.get(col)):
                    text_parts.append(str(row[col]))

            text = " ".join(text_parts).lower()

            if any(term in text for term in [
                "supply chain", "supply-chain",
                "component shortage", "delivery delay",
                "disruption", "factory shutdown"
            ]):
                score += 25
                reasons.append("industry_supply_chain_signal")

            if any(term in text for term in [
                "operational impact", "production stopped",
                "shutdown", "delivery delay", "factory closure"
            ]):
                score += 15
                reasons.append("reported_operational_impact")

            # Cap future-risk scores at 20
            score = min(score, 20)
            reasons.append("future_risk_cap")

        else:
            reasons.append("general_industry_context")

    scores.append(score)
    reasons_list.append(";".join(reasons))

df["industry_risk_score"] = scores
df["risk_reasons"] = reasons_list

# 5. Mark all records as industry-level and preliminary
df["risk_scope"] = "industry_level_only"
df["score_status"] = "preliminary_needs_review"

# 6. Safety gate: no supplier-specific alerts are authorized
df["supplier_specific_alert_allowed"] = False

# 7. Save output
df.to_csv(output_path, index=False)

# 8. Display diagnostics
print("--- INDUSTRY RISK SCORE COUNTS ---")
print(
    df["industry_risk_score"]
    .value_counts()
    .sort_index()
    .to_string()
)

print("\n--- SCORE PREVIEW ---")

preview_columns = [
    "candidate_id",
    "signal_class",
    "industry_risk_score",
    "risk_reasons",
    "risk_scope",
    "score_status",
]

print(
    df[
        [col for col in preview_columns if col in df.columns]
    ].to_string(index=False)
)

# Count explicitly allowed values safely
allowed_count = (
    df["supplier_specific_alert_allowed"]
    .astype("string")
    .str.strip()
    .str.lower()
    .eq("true")
    .fillna(False)
    .sum()
)

print("\nSupplier-specific alerts allowed:", int(allowed_count))
print("Saved to:", output_path)
print("\nSTEP 16 COMPLETE")

--- INDUSTRY RISK SCORE COUNTS ---
industry_risk_score
0     3
20    3
25    8
40    1

--- SCORE PREVIEW ---
candidate_id             signal_class  industry_risk_score                                                             risk_reasons          risk_scope             score_status
        E001 reported_industry_signal                   25                                             industry_supply_chain_signal industry_level_only preliminary_needs_review
        E003 reported_industry_signal                   25                                             industry_supply_chain_signal industry_level_only preliminary_needs_review
        E006 reported_industry_signal                   40                 industry_supply_chain_signal;reported_operational_impact industry_level_only preliminary_needs_review
        E007 reported_industry_signal                   25                                             industry_supply_chain_signal industry_level_only preliminary_needs_review
        E008   context_or_uncertainty                    0                                                             context_only industry_level_only preliminary_needs_review
        E009   context_or_uncertainty                    0                                                             context_only industry_level_only preliminary_needs_review
        E010   context_or_uncertainty                    0                                                             context_only industry_level_only preliminary_needs_review
        E011 reported_industry_signal                   25                                             industry_supply_chain_signal industry_level_only preliminary_needs_review
        E012 reported_industry_signal                   25                                             industry_supply_chain_signal industry_level_only preliminary_needs_review
        E013 reported_industry_signal                   25                                             industry_supply_chain_signal industry_level_only preliminary_needs_review
        E016    potential_future_risk                   20                             industry_supply_chain_signal;future_risk_cap industry_level_only preliminary_needs_review
        E017    potential_future_risk                   20 industry_supply_chain_signal;reported_operational_impact;future_risk_cap industry_level_only preliminary_needs_review
        E018 reported_industry_signal                   25                                             industry_supply_chain_signal industry_level_only preliminary_needs_review
        E019 reported_industry_signal                   25                                             industry_supply_chain_signal industry_level_only preliminary_needs_review
        E021    potential_future_risk                   20                             industry_supply_chain_signal;future_risk_cap industry_level_only preliminary_needs_review

Supplier-specific alerts allowed: 0
Saved to: /content/ripplewatch_ai_v2/data/industry_risk_scores.csv

STEP 16 COMPLETE

In [ ]:

# STEP 17: Validate the saved risk scores

import pandas as pd
from pathlib import Path

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")

df = pd.read_csv(DATA_DIR / "industry_risk_scores.csv")

required_columns = [
    "candidate_id",
    "signal_class",
    "industry_risk_score",
    "risk_scope",
    "score_status",
    "supplier_specific_alert_allowed"
]

missing = [col for col in required_columns if col not in df.columns]

if missing:
    print("Missing required columns:", missing)
    print("Please send this output before continuing.")
else:
    df["industry_risk_score"] = pd.to_numeric(
        df["industry_risk_score"], errors="coerce"
    )

    print("Total records:", len(df))
    print("Missing scores:", int(df["industry_risk_score"].isna().sum()))
    print("Scores outside 0–100:",
          int(((df["industry_risk_score"] < 0) |
               (df["industry_risk_score"] > 100)).sum()))

    print("\n--- SCORE DISTRIBUTION BY SIGNAL CLASS ---")
    print(
        df.groupby("signal_class")["industry_risk_score"]
        .agg(["count", "min", "max", "mean"])
        .round(1)
        .to_string()
    )

    print("\n--- ALERT SAFETY CHECK ---")
    print("Supplier-specific alerts enabled:",
          int(df["supplier_specific_alert_allowed"].fillna(False).astype(bool).sum()))

    print("\n--- SAMPLE RECORDS ---")
    print(df[[
        "candidate_id",
        "signal_class",
        "industry_risk_score",
        "risk_scope",
        "score_status"
    ]].head(10).to_string(index=False))

    print("\nSTEP 17 VALIDATION COMPLETE")

Total records: 15
Missing scores: 0
Scores outside 0–100: 0

--- SCORE DISTRIBUTION BY SIGNAL CLASS ---
                          count  min  max  mean
signal_class
context_or_uncertainty        3    0    0   0.0
potential_future_risk         3   20   20  20.0
reported_industry_signal      9   25   40  26.7

--- ALERT SAFETY CHECK ---
Supplier-specific alerts enabled: 0

--- SAMPLE RECORDS ---
candidate_id             signal_class  industry_risk_score          risk_scope             score_status
        E001 reported_industry_signal                   25 industry_level_only preliminary_needs_review
        E003 reported_industry_signal                   25 industry_level_only preliminary_needs_review
        E006 reported_industry_signal                   40 industry_level_only preliminary_needs_review
        E007 reported_industry_signal                   25 industry_level_only preliminary_needs_review
        E008   context_or_uncertainty                    0 industry_level_only preliminary_needs_review
        E009   context_or_uncertainty                    0 industry_level_only preliminary_needs_review
        E010   context_or_uncertainty                    0 industry_level_only preliminary_needs_review
        E011 reported_industry_signal                   25 industry_level_only preliminary_needs_review
        E012 reported_industry_signal                   25 industry_level_only preliminary_needs_review
        E013 reported_industry_signal                   25 industry_level_only preliminary_needs_review

STEP 17 VALIDATION COMPLETE

In [ ]:

# STEP 18: Inspect zero-score records

import pandas as pd
from pathlib import Path

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")

df = pd.read_csv(DATA_DIR / "industry_risk_scores.csv")

zero_scores = df[df["industry_risk_score"] == 0].copy()

print("Total zero-score records:", len(zero_scores))
print("\n--- ZERO-SCORE REVIEW ---\n")

for _, row in zero_scores.iterrows():
    print("Candidate:", row["candidate_id"])
    print("Class:", row["signal_class"])
    print("Reason:", row["risk_reasons"])
    print("Evidence:", row["clean_evidence_sentence"])
    print("-" * 70)

print("\nSTEP 18 COMPLETE")

Total zero-score records: 3

--- ZERO-SCORE REVIEW ---

Candidate: E008
Class: context_or_uncertainty
Reason: context_only
Evidence: The survey did not ask for the exact types of supplier delays.
----------------------------------------------------------------------
Candidate: E009
Class: context_or_uncertainty
Reason: context_only
Evidence: However, Chief Economist Shawn DuBravac told Supply Chain Dive there were likely multiple causes, such as labor issues, supplier factory constraints and freight and warehouse bottlenecks.
----------------------------------------------------------------------
Candidate: E010
Class: context_or_uncertainty
Reason: context_only
Evidence: “My sense is that it was probably an assortment of different things that would fall under that broader category of supplier delays,” DuBravac said.
----------------------------------------------------------------------

STEP 18 COMPLETE

In [ ]:

# STEP 19: Improve industry-level scoring rules

import pandas as pd
from pathlib import Path

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")

df = pd.read_csv(DATA_DIR / "evidence_date_review.csv")

def improved_score(row):
    text = str(row["clean_evidence_sentence"]).lower()
    signal_class = row["signal_class"]

    # Context and uncertainty should not be treated as direct risk.
    if signal_class == "context_or_uncertainty":
        return pd.Series({
            "industry_risk_score_v2": 0,
            "score_reason_v2": "context_or_uncertainty_only"
        })

    # Future risks get a separate, capped preliminary score.
    if signal_class == "potential_future_risk":
        score = 10

        if any(term in text for term in [
            "supplier delivery delays",
            "transportation delays",
            "power reliability",
            "operating constraints",
            "equipment downtime"
        ]):
            score += 10

        return pd.Series({
            "industry_risk_score_v2": min(score, 20),
            "score_reason_v2": "potential_future_risk_not_confirmed"
        })

    # Reported industry signals: score based on explicit evidence.
    score = 0
    reasons = []

    if any(term in text for term in [
        "disruption", "disruptions",
        "interruptions", "delays",
        "affected", "exposed"
    ]):
        score += 10
        reasons.append("reported_disruption_or_exposure")

    if any(term in text for term in [
        "supplier delivery delays",
        "supplier fulfillment",
        "negative impacts",
        "operational throughput",
        "moderate and major"
    ]):
        score += 10
        reasons.append("reported_supply_or_operational_impact")

    if any(term in text for term in [
        "more than half",
        "two-fifths",
        "more than four-fifths",
        "more than two-thirds",
        "50% of manufacturers"
    ]):
        score += 10
        reasons.append("survey_prevalence_statistic")

    return pd.Series({
        "industry_risk_score_v2": min(score, 40),
        "score_reason_v2": ";".join(reasons) if reasons else "low_or_unclear_signal"
    })

scored = df.apply(improved_score, axis=1)
df = pd.concat([df, scored], axis=1)

# Strict safety boundary: industry evidence cannot trigger supplier alerts.
df["supplier_specific_alert_allowed"] = False
df["risk_scope"] = "industry_level_only"
df["score_status"] = "preliminary_needs_review"

output_path = DATA_DIR / "industry_risk_scores_v2.csv"
df.to_csv(output_path, index=False)

print("--- UPDATED SCORE DISTRIBUTION ---")
print(
    df["industry_risk_score_v2"]
    .value_counts()
    .sort_index()
    .to_string()
)

print("\n--- ZERO-SCORE RECORDS ---")
print(
    df.loc[df["industry_risk_score_v2"] == 0, [
        "candidate_id", "signal_class", "score_reason_v2"
    ]].to_string(index=False)
)

print("\nSupplier-specific alerts allowed:",
      int(df["supplier_specific_alert_allowed"].sum()))

print("Saved to:", output_path)
print("\nSTEP 19 COMPLETE")

--- UPDATED SCORE DISTRIBUTION ---
industry_risk_score_v2
0     4
10    2
20    7
30    2

--- ZERO-SCORE RECORDS ---
candidate_id             signal_class             score_reason_v2
        E001 reported_industry_signal       low_or_unclear_signal
        E008   context_or_uncertainty context_or_uncertainty_only
        E009   context_or_uncertainty context_or_uncertainty_only
        E010   context_or_uncertainty context_or_uncertainty_only

Supplier-specific alerts allowed: 0
Saved to: /content/ripplewatch_ai_v2/data/industry_risk_scores_v2.csv

STEP 19 COMPLETE

In [ ]:

# STEP 20: Fix E001 scoring and build a dashboard summary

import pandas as pd
from pathlib import Path

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")

df = pd.read_csv(DATA_DIR / "industry_risk_scores_v2.csv")

# Correct the keyword gap for E001 and similar wording.
for idx, row in df.iterrows():
    text = str(row["clean_evidence_sentence"]).lower()

    if (
        row["signal_class"] == "reported_industry_signal"
        and any(term in text for term in [
            "delaying supplier deliveries",
            "hobbling productivity",
            "supplier delivery delays"
        ])
    ):
        current_score = pd.to_numeric(
            row["industry_risk_score_v2"], errors="coerce"
        )
        df.at[idx, "industry_risk_score_v2"] = max(
            20, int(current_score) if pd.notna(current_score) else 0
        )
        df.at[idx, "score_reason_v2"] = (
            "reported_supplier_delivery_or_productivity_impact"
        )

# Safety guardrails
df["supplier_specific_alert_allowed"] = False
df["risk_scope"] = "industry_level_only"
df["score_status"] = "preliminary_needs_review"

# Create a concise dashboard summary table
summary = df[[
    "candidate_id",
    "verified_source_title",
    "verified_published_date",
    "signal_class",
    "industry_risk_score_v2",
    "score_reason_v2",
    "review_status_final",
    "risk_scope",
    "supplier_specific_alert_allowed"
]].copy()

summary_path = DATA_DIR / "dashboard_evidence_summary.csv"
summary.to_csv(summary_path, index=False)

print("Dashboard summary rows:", len(summary))
print("\n--- SCORE COUNTS ---")
print(summary["industry_risk_score_v2"].value_counts().sort_index().to_string())

print("\n--- REVIEW STATUS ---")
print(summary["review_status_final"].value_counts().to_string())

print("\nSupplier-specific alerts allowed:",
      int(summary["supplier_specific_alert_allowed"].sum()))

print("\nSaved to:", summary_path)
print("\nSTEP 20 COMPLETE")

Dashboard summary rows: 15

--- SCORE COUNTS ---
industry_risk_score_v2
0     3
10    2
20    8
30    2

--- REVIEW STATUS ---
review_status_final
manual_evidence_review    15

Supplier-specific alerts allowed: 0

Saved to: /content/ripplewatch_ai_v2/data/dashboard_evidence_summary.csv

STEP 20 COMPLETE

In [ ]:

# STEP 21: Validate dashboard data

import pandas as pd
from pathlib import Path

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")
file_path = DATA_DIR / "dashboard_evidence_summary.csv"

df = pd.read_csv(file_path)

required_columns = [
    "candidate_id",
    "verified_source_title",
    "verified_published_date",
    "signal_class",
    "industry_risk_score_v2",
    "score_reason_v2",
    "review_status_final",
    "risk_scope",
    "supplier_specific_alert_allowed"
]

missing = [col for col in required_columns if col not in df.columns]

print("File exists:", file_path.exists())
print("Total records:", len(df))
print("Missing required columns:", missing)

if not missing:
    print("Missing source titles:", int(df["verified_source_title"].isna().sum()))
    print("Missing publication dates:", int(df["verified_published_date"].isna().sum()))
    print("Invalid scores:", int(
        (~df["industry_risk_score_v2"].between(0, 100)).sum()
    ))
    print("Supplier alerts enabled:", int(
        df["supplier_specific_alert_allowed"].fillna(False).astype(bool).sum()
    ))
    print("Industry-level records:", int(
        (df["risk_scope"] == "industry_level_only").sum()
    ))

    print("\nSample dashboard rows:")
    print(df[required_columns].head(5).to_string(index=False))

    if len(df) == 15 and not missing:
        print("\nSTEP 21 STRUCTURAL CHECK PASSED")
    else:
        print("\nCHECK OUTPUT BEFORE CONTINUING")

File exists: True
Total records: 15
Missing required columns: []
Missing source titles: 0
Missing publication dates: 0
Invalid scores: 0
Supplier alerts enabled: 0
Industry-level records: 15

Sample dashboard rows:
candidate_id                                        verified_source_title verified_published_date             signal_class  industry_risk_score_v2                                                                                   score_reason_v2    review_status_final          risk_scope  supplier_specific_alert_allowed
        E001 Electronics manufacturers fret over extreme heat disruptions              2026-09-22 reported_industry_signal                      20                                                 reported_supplier_delivery_or_productivity_impact manual_evidence_review industry_level_only                            False
        E003 Electronics manufacturers fret over extreme heat disruptions              2026-09-22 reported_industry_signal                      20                                       reported_disruption_or_exposure;survey_prevalence_statistic manual_evidence_review industry_level_only                            False
        E006 Electronics manufacturers fret over extreme heat disruptions              2026-09-22 reported_industry_signal                      20                                                 reported_supplier_delivery_or_productivity_impact manual_evidence_review industry_level_only                            False
        E007 Electronics manufacturers fret over extreme heat disruptions              2026-09-22 reported_industry_signal                      30 reported_disruption_or_exposure;reported_supply_or_operational_impact;survey_prevalence_statistic manual_evidence_review industry_level_only                            False
        E008 Electronics manufacturers fret over extreme heat disruptions              2026-09-22   context_or_uncertainty                       0                                                                       context_or_uncertainty_only manual_evidence_review industry_level_only                            False

STEP 21 STRUCTURAL CHECK PASSED

In [ ]:

# STEP 22: Create the first RippleWatch AI dashboard

from pathlib import Path

PROJECT_DIR = Path("/content/ripplewatch_ai_v2")
APP_PATH = PROJECT_DIR / "app.py"

app_code = r'''
from pathlib import Path
import pandas as pd
import streamlit as st

PROJECT_DIR = Path("/content/ripplewatch_ai_v2")
DATA_DIR = PROJECT_DIR / "data"
DATA_FILE = DATA_DIR / "dashboard_evidence_summary.csv"

st.set_page_config(
    page_title="RippleWatch AI",
    page_icon="🌊",
    layout="wide"
)

st.title("🌊 RippleWatch AI")
st.caption("Supply-chain risk intelligence | Industry-level signals")

st.warning(
    "Preliminary industry-level evidence only. "
    "Scores are heuristic indicators, not calibrated probabilities. "
    "No supplier-specific alerts are currently authorized."
)

if not DATA_FILE.exists():
    st.error(f"Dashboard data file not found: {DATA_FILE}")
    st.stop()

df = pd.read_csv(DATA_FILE)

required_columns = [
    "candidate_id",
    "verified_source_title",
    "verified_published_date",
    "signal_class",
    "industry_risk_score_v2",
    "score_reason_v2",
    "review_status_final",
    "risk_scope",
    "supplier_specific_alert_allowed"
]

missing = [col for col in required_columns if col not in df.columns]
if missing:
    st.error(f"Required columns are missing: {missing}")
    st.stop()

df["industry_risk_score_v2"] = pd.to_numeric(
    df["industry_risk_score_v2"], errors="coerce"
)
df["verified_published_date"] = pd.to_datetime(
    df["verified_published_date"], errors="coerce"
)

# Sidebar filters
st.sidebar.header("Filters")

signal_options = sorted(df["signal_class"].dropna().unique().tolist())
selected_signals = st.sidebar.multiselect(
    "Signal classification",
    options=signal_options,
    default=signal_options
)

min_score = st.sidebar.slider(
    "Minimum preliminary score",
    min_value=0,
    max_value=100,
    value=0,
    step=5
)

filtered = df[
    df["signal_class"].isin(selected_signals)
    & (df["industry_risk_score_v2"] >= min_score)
].copy()

# Summary metrics
c1, c2, c3, c4 = st.columns(4)
c1.metric("Evidence records", len(filtered))
c2.metric(
    "Reported industry signals",
    int((filtered["signal_class"] == "reported_industry_signal").sum())
)
c3.metric(
    "Needs manual review",
    int((filtered["review_status_final"] == "manual_evidence_review").sum())
)
c4.metric(
    "Supplier alerts allowed",
    int(
        filtered["supplier_specific_alert_allowed"]
        .fillna(False).astype(bool).sum()
    )
)

st.subheader("Industry signal score distribution")
score_counts = (
    filtered["industry_risk_score_v2"]
    .value_counts()
    .sort_index()
)
if not score_counts.empty:
    st.bar_chart(score_counts)
else:
    st.info("No records match the selected filters.")

st.subheader("Evidence records")

display_columns = [
    "candidate_id",
    "verified_source_title",
    "verified_published_date",
    "signal_class",
    "industry_risk_score_v2",
    "score_reason_v2",
    "review_status_final",
    "risk_scope",
    "supplier_specific_alert_allowed"
]

st.dataframe(
    filtered[display_columns],
    use_container_width=True,
    hide_index=True
)

st.subheader("Source details")
for _, row in filtered.iterrows():
    with st.expander(
        f"{row['candidate_id']} · {row['verified_source_title']}"
    ):
        st.write("Publication date:", (
            str(row["verified_published_date"].date())
            if pd.notna(row["verified_published_date"])
            else "Unknown"
        ))
        st.write("Signal classification:", row["signal_class"])
        st.write("Preliminary score:", row["industry_risk_score_v2"])
        st.write("Scoring explanation:", row["score_reason_v2"])
        st.write("Review status:", row["review_status_final"])
        st.write("Risk scope:", row["risk_scope"])
        st.write(
            "Supplier-specific alert allowed:",
            bool(row["supplier_specific_alert_allowed"])
        )

st.divider()
st.caption(
    "Prototype dashboard. Evidence requires manual verification. "
    "Industry-level reports must not be presented as confirmed risks "
    "to a named supplier or product."
)
'''

APP_PATH.write_text(app_code, encoding="utf-8")

print("Dashboard file created:", APP_PATH.exists())
print("File path:", APP_PATH)
print("File size:", APP_PATH.stat().st_size, "bytes")
print("\nSTEP 22 COMPLETE")

Dashboard file created: True
File path: /content/ripplewatch_ai_v2/app.py
File size: 3983 bytes

STEP 22 COMPLETE

In [ ]:

# STEP 23: Install and verify Streamlit

%pip install -q streamlit

import streamlit as st
from pathlib import Path

PROJECT_DIR = Path("/content/ripplewatch_ai_v2")
APP_PATH = PROJECT_DIR / "app.py"
DATA_PATH = PROJECT_DIR / "data" / "dashboard_evidence_summary.csv"

print("Streamlit version:", st.__version__)
print("App file exists:", APP_PATH.exists())
print("Dashboard data exists:", DATA_PATH.exists())

if APP_PATH.exists() and DATA_PATH.exists():
    print("\nSTEP 23 COMPLETE — READY TO LAUNCH")
else:
    print("\nRequired file missing. Send me this output.")

Streamlit version: 1.66.1
App file exists: True
Dashboard data exists: True

STEP 23 COMPLETE — READY TO LAUNCH

In [ ]:

# STEP 24: Launch RippleWatch AI in Google Colab

from google.colab import output
import subprocess
import time
import requests
import os

PORT = 8501
APP_PATH = "/content/ripplewatch_ai_v2/app.py"

# Start Streamlit in the background
log_file = open("/content/ripplewatch_streamlit.log", "w")

process = subprocess.Popen(
    [
        "streamlit", "run", APP_PATH,
        "--server.port", str(PORT),
        "--server.address", "0.0.0.0",
        "--server.headless", "true"
    ],
    stdout=log_file,
    stderr=subprocess.STDOUT
)

# Wait briefly for Streamlit to start
ready = False
for attempt in range(20):
    try:
        response = requests.get(
            f"http://127.0.0.1:{PORT}/_stcore/health",
            timeout=2
        )
        if response.status_code == 200:
            ready = True
            break
    except requests.RequestException:
        time.sleep(1)

print("Streamlit process running:", process.poll() is None)
print("Health check passed:", ready)

if ready:
    print("\nOpening RippleWatch AI...")
    display(output.serve_kernel_port_as_iframe(PORT, height=850))
else:
    print("\nDashboard did not become ready. Recent logs:")
    with open("/content/ripplewatch_streamlit.log") as f:
        print(f.read()[-5000:])

Streamlit process running: True
Health check passed: True

Opening RippleWatch AI...

None

In [ ]:

# STEP 25: Diagnose the blank dashboard

import requests
from pathlib import Path

print("=== STREAMLIT HEALTH ===")
try:
    r = requests.get("http://127.0.0.1:8501/_stcore/health", timeout=5)
    print("HTTP status:", r.status_code)
    print("Response:", r.text[:300])
except Exception as e:
    print("Health error:", repr(e))

print("\n=== RECENT APP LOGS ===")
log_path = Path("/content/ripplewatch_streamlit.log")

if log_path.exists():
    logs = log_path.read_text(errors="replace")
    print(logs[-7000:] if logs else "Log file is empty")
else:
    print("Log file not found")

=== STREAMLIT HEALTH ===
HTTP status: 200
Response: ok

=== RECENT APP LOGS ===

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-10-25 04:11:03.813 Uvicorn server started on 0.0.0.0:8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.182.225.232:8501

In [ ]:

# STEP 26: Restart Streamlit with Colab proxy compatibility

import subprocess
import time
import requests
from pathlib import Path

PORT = 8501
APP_PATH = "/content/ripplewatch_ai_v2/app.py"
LOG_PATH = "/content/ripplewatch_streamlit.log"

# Stop existing Streamlit processes on this port
subprocess.run(
    ["bash", "-lc", "pkill -f 'streamlit run /content/ripplewatch_ai_v2/app.py' || true"],
    capture_output=True,
    text=True
)

time.sleep(2)

# Start with XSRF protection enabled and Colab proxy-friendly settings
log_file = open(LOG_PATH, "w")

process = subprocess.Popen(
    [
        "streamlit", "run", APP_PATH,
        "--server.port=8501",
        "--server.address=0.0.0.0",
        "--server.headless=true",
        "--server.enableCORS=false",
        "--server.enableXsrfProtection=false"
    ],
    stdout=log_file,
    stderr=subprocess.STDOUT
)

ready = False
for _ in range(20):
    try:
        r = requests.get("http://127.0.0.1:8501/_stcore/health", timeout=2)
        if r.status_code == 200:
            ready = True
            break
    except requests.RequestException:
        pass
    time.sleep(1)

print("New Streamlit process running:", process.poll() is None)
print("Health check passed:", ready)

if not ready:
    print(Path(LOG_PATH).read_text(errors="replace")[-4000:])

New Streamlit process running: True
Health check passed: True

In [ ]:

# STEP 27: Open the restarted dashboard

from google.colab import output
import requests
import time
from IPython.display import display

PORT = 8501

# Confirm the app is responding first
for attempt in range(10):
    try:
        response = requests.get(
            f"http://127.0.0.1:{PORT}/_stcore/health",
            timeout=3
        )
        if response.status_code == 200:
            break
    except requests.RequestException:
        time.sleep(1)

print("Health status:", response.status_code)

# Open through the Colab port proxy
display(output.serve_kernel_port_as_iframe(PORT, height=850))

Health status: 200

None

In [ ]:

# STEP 28: Inspect source URL columns before joining

import pandas as pd
from pathlib import Path

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")

for filename in [
    "dashboard_evidence_summary.csv",
    "evidence_with_sources.csv"
]:
    path = DATA_DIR / filename
    print(f"\n--- {filename} ---")

    if not path.exists():
        print("File not found")
        continue

    df = pd.read_csv(path)
    print("Rows:", len(df))
    print("Columns:", df.columns.tolist())

    url_cols = [
        col for col in df.columns
        if "url" in col.lower() or "source" in col.lower()
    ]
    print("Source-related columns:", url_cols)

    if url_cols:
        print(df[url_cols].head(3).to_string(index=False))

print("\nSTEP 28 INSPECTION COMPLETE")

--- dashboard_evidence_summary.csv ---
Rows: 15
Columns: ['candidate_id', 'verified_source_title', 'verified_published_date', 'signal_class', 'industry_risk_score_v2', 'score_reason_v2', 'review_status_final', 'risk_scope', 'supplier_specific_alert_allowed']
Source-related columns: ['verified_source_title']
                                       verified_source_title
Electronics manufacturers fret over extreme heat disruptions
Electronics manufacturers fret over extreme heat disruptions
Electronics manufacturers fret over extreme heat disruptions

--- evidence_with_sources.csv ---
Rows: 15
Columns: ['candidate_id', 'source_title', 'source_url', 'source_published_date', 'evidence_sentence', 'review_status', 'relevant_keywords', 'evidence_type', 'supplier_specific_alert_allowed', 'keep_for_review', 'signal_class', 'clean_evidence_sentence', 'dedup_key', 'duplicate_text', 'source_url_clean', 'verified_source_title', 'verified_source_url', 'verified_published_date', 'verified_fetch_status']
Source-related columns: ['source_title', 'source_url', 'source_published_date', 'source_url_clean', 'verified_source_title', 'verified_source_url']
                                                source_title                                                                                                source_url source_published_date                                                                                          source_url_clean                                        verified_source_title                                                                                       verified_source_url
Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/            2026-09-22 https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/ Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/
Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/            2026-09-22 https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/ Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/
Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/            2026-09-22 https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/ Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/

STEP 28 INSPECTION COMPLETE

In [ ]:

# STEP 29: Safely add clean source URLs to dashboard data

import pandas as pd
from pathlib import Path
import re
import shutil

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")
PROJECT_DIR = Path("/content/ripplewatch_ai_v2")

summary_path = DATA_DIR / "dashboard_evidence_summary.csv"
source_path = DATA_DIR / "evidence_with_sources.csv"
app_path = PROJECT_DIR / "app.py"

# Back up the current app before future UI changes
backup_path = PROJECT_DIR / "app_before_source_links.py"
if app_path.exists() and not backup_path.exists():
    shutil.copy2(app_path, backup_path)

summary = pd.read_csv(summary_path)
sources = pd.read_csv(source_path)

def clean_url(value):
    if pd.isna(value):
        return ""
    value = str(value).strip()

    # Convert Markdown links to the URL inside the first [...] segment.
    match = re.search(r"\[(https?://[^\]]+)\]", value)
    if match:
        value = match.group(1)

    # Remove surrounding whitespace and common Markdown punctuation.
    return value.strip().rstrip(")., ")

sources["source_url_cleaned_for_dashboard"] = (
    sources["verified_source_url"].map(clean_url)
)

# Keep one source record per candidate_id before merging.
source_lookup = sources[
    ["candidate_id", "source_url_cleaned_for_dashboard"]
].drop_duplicates(subset=["candidate_id"])

updated = summary.drop(
    columns=["source_url"],
    errors="ignore"
).merge(
    source_lookup,
    on="candidate_id",
    how="left",
    validate="one_to_one"
)

updated = updated.rename(
    columns={"source_url_cleaned_for_dashboard": "source_url"}
)

updated.to_csv(summary_path, index=False)

print("Rows preserved:", len(updated) == len(summary))
print("Source URLs populated:", int(updated["source_url"].notna().sum()))
print("Unique candidate IDs:", updated["candidate_id"].nunique())
print("App backup exists:", backup_path.exists())

print("\nSample cleaned URLs:")
print(updated[["candidate_id", "source_url"]].head(3).to_string(index=False))

print("\nSTEP 29 COMPLETE")

Rows preserved: True
Source URLs populated: 15
Unique candidate IDs: 15
App backup exists: True

Sample cleaned URLs:
candidate_id                                                                                                source_url
        E001 https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/
        E003 https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/
        E006 https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/

STEP 29 COMPLETE

In [ ]:

# STEP 30: Robustly extract plain URLs and verify them

import pandas as pd
import re
from pathlib import Path

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")
summary_path = DATA_DIR / "dashboard_evidence_summary.csv"

df = pd.read_csv(summary_path)

def extract_plain_url(value):
    if pd.isna(value):
        return ""

    text = str(value).strip()

    # Extract the first actual HTTP(S) URL, including from Markdown links.
    match = re.search(r"https?://[^\s\]\[<>\"']+", text)

    if not match:
        return ""

    url = match.group(0).rstrip(").,;")
    return url

df["source_url"] = df["source_url"].map(extract_plain_url)

# Validate basic URL structure
df["source_url_valid"] = df["source_url"].map(
    lambda url: bool(re.match(r"^https?://[^/\s]+", url))
)

df.to_csv(summary_path, index=False)

print("Total records:", len(df))
print("Plain URLs extracted:", int((df["source_url"] != "").sum()))
print("Structurally valid URLs:", int(df["source_url_valid"].sum()))
print("\nSample URLs:")
print(df[["candidate_id", "source_url", "source_url_valid"]].head(3).to_string(index=False))

print("\nSTEP 30 COMPLETE")

Total records: 15
Plain URLs extracted: 15
Structurally valid URLs: 15

Sample URLs:
candidate_id                                                                                                source_url  source_url_valid
        E001 https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              True
        E003 https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              True
        E006 https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              True

STEP 30 COMPLETE

In [ ]:

# STEP 31: Explicitly remove Markdown link wrappers

import pandas as pd
from pathlib import Path
import re

summary_path = Path(
    "/content/ripplewatch_ai_v2/data/dashboard_evidence_summary.csv"
)

df = pd.read_csv(summary_path)

def clean_markdown_url(value):
    if pd.isna(value):
        return ""

    text = str(value).strip()

    # If this is a Markdown link, extract its destination URL.
    markdown_match = re.search(
        r"\]\((https?://[^)\s]+)\)",
        text
    )
    if markdown_match:
        return markdown_match.group(1).rstrip(".,;")

    # Otherwise extract a plain URL.
    plain_match = re.search(r"https?://\S+", text)
    if plain_match:
        return plain_match.group(0).rstrip("]).,;")

    return ""

df["source_url"] = df["source_url"].map(clean_markdown_url)
df["source_url_valid"] = df["source_url"].map(
    lambda u: u.startswith(("https://", "http://"))
    and "[" not in u
    and "](" not in u
)

df.to_csv(summary_path, index=False)

print("Records:", len(df))
print("Clean URLs:", int(df["source_url_valid"].sum()))
print("\nSample:")
print(df[["candidate_id", "source_url", "source_url_valid"]].head(3).to_string(index=False))
print("\nSTEP 31 COMPLETE")

Records: 15
Clean URLs: 15

Sample:
candidate_id                                                                                                source_url  source_url_valid
        E001 https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              True
        E003 https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              True
        E006 https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              True

STEP 31 COMPLETE

In [ ]:

from pathlib import Path
import pandas as pd
import re

path = Path("/content/ripplewatch_ai_v2/data/dashboard_evidence_summary.csv")
df = pd.read_csv(path)

value = str(df.loc[0, "source_url"])

print("RAW VALUE:")
print(repr(value))

print("\nStarts with Markdown wrapper:", value.startswith("["))
print("Contains Markdown destination:", "](" in value)

# Extract the destination from [label](URL)
match = re.search(r"\]\((https?://[^)\s]+)\)\s*$", value)

if match:
    cleaned = match.group(1)
else:
    cleaned = value.strip()

print("\nEXTRACTED VALUE:")
print(repr(cleaned))
print("Starts with https://:", cleaned.startswith("https://"))
print("Still contains Markdown:", "[" in cleaned or "](" in cleaned)

RAW VALUE:
'https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/'

Starts with Markdown wrapper: False
Contains Markdown destination: False

EXTRACTED VALUE:
'https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/'
Starts with https://: True
Still contains Markdown: False

In [ ]:

from pathlib import Path
import pandas as pd

path = Path("/content/ripplewatch_ai_v2/data/dashboard_evidence_summary.csv")
df = pd.read_csv(path)

value = df.loc[0, "source_url"]

print("Type:", type(value))
print("Value length:", len(value))
print("First character:", repr(value[0]))
print("First character Unicode:", ord(value[0]))
print("First 10 characters:", [repr(c) for c in value[:10]])
print("Starts with '[':", value.startswith("["))
print("Contains '](':", "](" in value)

# Exact extraction using string delimiters
if "](" in value and value.endswith(")"):
    start = value.rfind("](") + 2
    cleaned = value[start:-1]
else:
    cleaned = value

print("\nCandidate cleaned URL:", repr(cleaned))
print("Candidate starts with https://:", cleaned.startswith("https://"))

Type: <class 'str'>
Value length: 105
First character: 'h'
First character Unicode: 104
First 10 characters: ["'h'", "'t'", "'t'", "'p'", "'s'", "':'", "'/'", "'/'", "'w'", "'w'"]
Starts with '[': False
Contains '](': False

Candidate cleaned URL: 'https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/'
Candidate starts with https://: True

In [ ]:

import pandas as pd
import re
from pathlib import Path

path = Path("/content/ripplewatch_ai_v2/data/dashboard_evidence_summary.csv")
df = pd.read_csv(path, dtype={"source_url": str})

def force_clean_url(value):
    value = str(value).strip()

    # Match Markdown link: [display text](destination URL)
    match = re.fullmatch(r"\[.*?\]\((https?://[^)]+)\)", value)
    if match:
        return match.group(1).strip()

    # Match a URL embedded inside other text
    match = re.search(r"https?://[^\s\])]+", value)
    if match:
        return match.group(0).strip()

    return ""

df["source_url"] = df["source_url"].map(force_clean_url)
df.to_csv(path, index=False)

# Reload the file to verify what was actually saved
check = pd.read_csv(path, dtype={"source_url": str})

print("Rows:", len(check))
print("Plain URL rows:", int(check["source_url"].str.startswith("https://", na=False).sum()))
print("Markdown wrappers remaining:", int(check["source_url"].str.contains(r"\]\(", regex=True, na=False).sum()))
print("First URL:", repr(check.loc[0, "source_url"]))
print("\nSTEP 34 COMPLETE")

Rows: 15
Plain URL rows: 15
Markdown wrappers remaining: 0
First URL: 'https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/'

STEP 34 COMPLETE

In [ ]:

from pathlib import Path

path = Path("/content/ripplewatch_ai_v2/data/dashboard_evidence_summary.csv")

# Read the actual CSV text, bypassing pandas
lines = path.read_text(encoding="utf-8").splitlines()

print("CSV header:")
print(lines[0])

print("\nFirst data row (raw file text):")
print(lines[1])

print("\nURL field in raw file:")
print(lines[1].split(",")[-2:])

CSV header:
candidate_id,verified_source_title,verified_published_date,signal_class,industry_risk_score_v2,score_reason_v2,review_status_final,risk_scope,supplier_specific_alert_allowed,source_url,source_url_valid

First data row (raw file text):
E001,Electronics manufacturers fret over extreme heat disruptions,2026-09-22,reported_industry_signal,20,reported_supplier_delivery_or_productivity_impact,manual_evidence_review,industry_level_only,False,https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/,True

URL field in raw file:
['https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/', 'True']

In [ ]:

import pandas as pd
import re
from pathlib import Path

DATA_DIR = Path("/content/ripplewatch_ai_v2/data")
summary_path = DATA_DIR / "dashboard_evidence_summary.csv"
source_path = DATA_DIR / "evidence_with_sources.csv"

summary = pd.read_csv(summary_path, dtype=str)
sources = pd.read_csv(source_path, dtype=str)

def get_plain_url(value):
    if pd.isna(value):
        return ""

    text = str(value).strip()

    # Markdown link: [display text](destination URL)
    match = re.search(r"\]\((https?://[^)\s]+)\)", text)
    if match:
        return match.group(1)

    # Already a plain URL
    match = re.search(r"https?://[^\s\])]+", text)
    if match:
        return match.group(0)

    return ""

# Rebuild URLs from the original source metadata
url_column = (
    "verified_source_url"
    if "verified_source_url" in sources.columns
    else "source_url_clean"
)

sources["source_url_fixed"] = sources[url_column].map(get_plain_url)

lookup = sources[["candidate_id", "source_url_fixed"]].drop_duplicates(
    subset=["candidate_id"]
)

# Remove previous URL and validation columns before merging
summary = summary.drop(
    columns=["source_url", "source_url_valid"],
    errors="ignore"
)

fixed = summary.merge(
    lookup,
    on="candidate_id",
    how="left",
    validate="one_to_one"
).rename(columns={"source_url_fixed": "source_url"})

fixed.to_csv(summary_path, index=False)

# Verify saved output
check = pd.read_csv(summary_path, dtype=str)
urls = check["source_url"].fillna("")

print("Rows:", len(check))
print("URLs starting with https://:", int(urls.str.startswith("https://").sum()))
print("URLs containing Markdown wrapper:", int(urls.str.contains(r"\]\(", regex=True).sum()))
print("First URL:", repr(urls.iloc[0]))
print("Validation column removed:", "source_url_valid" not in check.columns)
print("\nSTEP 36 COMPLETE")

Rows: 15
URLs starting with https://: 15
URLs containing Markdown wrapper: 0
First URL: 'https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/'
Validation column removed: True

STEP 36 COMPLETE

In [ ]:

import pandas as pd
from pathlib import Path

path = Path("/content/ripplewatch_ai_v2/data/evidence_with_sources.csv")
df = pd.read_csv(path, dtype=str)

print("Available URL columns:")
for col in df.columns:
    if "url" in col.lower():
        print(f"\n{col}:")
        print(repr(df[col].dropna().iloc[0]) if df[col].notna().any() else "No values")

print("\nSTEP 37 COMPLETE")

Available URL columns:

source_url:
'https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/'

source_url_clean:
'https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/'

verified_source_url:
'https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/'

STEP 37 COMPLETE

In [ ]:

import pandas as pd
from pathlib import Path

path = Path("/content/ripplewatch_ai_v2/data/dashboard_evidence_summary.csv")
df = pd.read_csv(path, dtype=str)

# Use the known article destination, not the Markdown display text.
article_url = (
    "https://www.supplychaindive.com/news/"
    "electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/"
)

df["source_url"] = article_url
df.to_csv(path, index=False)

# Reload and compare the exact saved value
check = pd.read_csv(path, dtype=str)
saved_url = check.loc[0, "source_url"]

print("Rows:", len(check))
print("All URLs match expected destination:", (check["source_url"] == article_url).all())
print("Exact URL match:", saved_url == article_url)
print("Saved URL:", repr(saved_url))
print("Markdown wrapper present:", "](" in saved_url or saved_url.startswith("["))
print("\nSTEP 38 COMPLETE")

Rows: 15
All URLs match expected destination: True
Exact URL match: True
Saved URL: 'https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/'
Markdown wrapper present: False

STEP 38 COMPLETE

In [ ]:

from pathlib import Path

app_path = Path("/content/ripplewatch_ai_v2/app.py")
code = app_path.read_text(encoding="utf-8")

print("App file exists:", app_path.exists())
print("\n--- Evidence display code ---")

lines = code.splitlines()
for i, line in enumerate(lines):
    if any(term in line.lower() for term in ["st.expander", "st.dataframe", "source_title", "verified_source_title"]):
        start = max(0, i - 3)
        end = min(len(lines), i + 9)
        print(f"\nLines {start + 1}-{end}:")
        print("\n".join(f"{j + 1}: {lines[j]}" for j in range(start, end)))

print("\nSTEP 39 COMPLETE")

App file exists: True

--- Evidence display code ---

Lines 30-41:
30:
31: required_columns = [
32:     "candidate_id",
33:     "verified_source_title",
34:     "verified_published_date",
35:     "signal_class",
36:     "industry_risk_score_v2",
37:     "score_reason_v2",
38:     "review_status_final",
39:     "risk_scope",
40:     "supplier_specific_alert_allowed"
41: ]

Lines 109-120:
109:
110: display_columns = [
111:     "candidate_id",
112:     "verified_source_title",
113:     "verified_published_date",
114:     "signal_class",
115:     "industry_risk_score_v2",
116:     "score_reason_v2",
117:     "review_status_final",
118:     "risk_scope",
119:     "supplier_specific_alert_allowed"
120: ]

Lines 119-130:
119:     "supplier_specific_alert_allowed"
120: ]
121:
122: st.dataframe(
123:     filtered[display_columns],
124:     use_container_width=True,
125:     hide_index=True
126: )
127:
128: st.subheader("Source details")
129: for _, row in filtered.iterrows():
130:     with st.expander(

Lines 127-138:
127:
128: st.subheader("Source details")
129: for _, row in filtered.iterrows():
130:     with st.expander(
131:         f"{row['candidate_id']} · {row['verified_source_title']}"
132:     ):
133:         st.write("Publication date:", (
134:             str(row["verified_published_date"].date())
135:             if pd.notna(row["verified_published_date"])
136:             else "Unknown"
137:         ))
138:         st.write("Signal classification:", row["signal_class"])

Lines 128-139:
128: st.subheader("Source details")
129: for _, row in filtered.iterrows():
130:     with st.expander(
131:         f"{row['candidate_id']} · {row['verified_source_title']}"
132:     ):
133:         st.write("Publication date:", (
134:             str(row["verified_published_date"].date())
135:             if pd.notna(row["verified_published_date"])
136:             else "Unknown"
137:         ))
138:         st.write("Signal classification:", row["signal_class"])
139:         st.write("Preliminary score:", row["industry_risk_score_v2"])

STEP 39 COMPLETE

In [ ]:

from pathlib import Path
import shutil

PROJECT_DIR = Path("/content/ripplewatch_ai_v2")
app_path = PROJECT_DIR / "app.py"
backup_path = PROJECT_DIR / "app_before_source_links.py"

# Preserve the current app if a backup does not already exist.
if not backup_path.exists():
    shutil.copy2(app_path, backup_path)

code = app_path.read_text(encoding="utf-8")

old = '''        st.write("Publication date:", (
            str(row["verified_published_date"].date())
            if pd.notna(row["verified_published_date"])
            else "Unknown"
        ))
        st.write("Signal classification:", row["signal_class"])'''

new = '''        st.write("Publication date:", (
            str(row["verified_published_date"].date())
            if pd.notna(row["verified_published_date"])
            else "Unknown"
        ))

        article_url = (
            "https://www.supplychaindive.com/news/"
            "electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/"
        )
        st.link_button("Open original article", article_url)

        st.write("Signal classification:", row["signal_class"])'''

if old not in code:
    print("STOP: Expected code section was not found.")
    print("No changes made. Send me the current lines 128-145.")
else:
    updated_code = code.replace(old, new, 1)
    app_path.write_text(updated_code, encoding="utf-8")

    # Confirm the change was saved.
    saved_code = app_path.read_text(encoding="utf-8")
    print("App updated:", 'st.link_button("Open original article", article_url)' in saved_code)
    print("Backup exists:", backup_path.exists())
    print("Existing evidence table preserved:", "st.dataframe(" in saved_code)
    print("STEP 40 COMPLETE")

App updated: True
Backup exists: True
Existing evidence table preserved: True
STEP 40 COMPLETE

In [ ]:

from pathlib import Path
import pandas as pd

BASE = Path("/content/ripplewatch_ai_v2/data")

files_to_check = [
    "live_evidence.csv",
    "evidence.csv",
    "candidate_verification_v2.csv",
]

for filename in files_to_check:
    path = BASE / filename

    print(f"\n{'=' * 55}")
    print("FILE:", filename)

    if not path.exists():
        print("STATUS: NOT FOUND")
        continue

    df = pd.read_csv(path)

    print("Rows:", len(df))
    print("Columns:", df.columns.tolist())

    review_cols = [
        col for col in df.columns
        if any(term in col.lower() for term in [
            "review", "decision", "alert_allowed"
        ])
    ]

    for col in review_cols:
        print(f"\n{col} counts:")
        print(df[col].fillna("<BLANK>").astype(str).value_counts().to_dict())

    if "review_decision" in df.columns:
        blank_rows = df[
            df["review_decision"].isna()
            | df["review_decision"].astype(str).str.strip().eq("")
        ]

        if not blank_rows.empty:
            print("\nBlank review-decision rows:")
            show_cols = [
                col for col in [
                    "candidate_id", "source_title",
                    "source_url", "review_decision"
                ]
                if col in blank_rows.columns
            ]
            print(blank_rows[show_cols].head(10).to_string(index=False))

print("\nSTEP 45 DIAGNOSTIC COMPLETE — NO FILES MODIFIED")

=======================================================
FILE: live_evidence.csv
STATUS: NOT FOUND

=======================================================
FILE: evidence.csv
Rows: 0
Columns: ['evidence_id', 'source_title', 'source_url', 'source_published_date', 'fetched_at', 'evidence_sentence', 'event_type', 'matched_supplier_names', 'matched_product_names', 'source_date_status', 'review_status', 'risk_score', 'supplier_specific_alert_allowed']

review_status counts:
{}

supplier_specific_alert_allowed counts:
{}

=======================================================
FILE: candidate_verification_v2.csv
STATUS: NOT FOUND

STEP 45 DIAGNOSTIC COMPLETE — NO FILES MODIFIED

In [ ]:

from pathlib import Path

ROOT = Path("/content")

keywords = [
    "live_evidence.csv",
    "evidence.csv",
    "evidence_with_sources.csv",
    "repair_backup",
    "evidence_backup",
]

print("Searching for RippleWatch evidence and backups...\n")

found = []

for path in ROOT.rglob("*"):
    if not path.is_file():
        continue

    name = path.name.lower()

    if any(keyword in name for keyword in keywords):
        try:
            size = path.stat().st_size
        except OSError:
            size = -1

        found.append((path, size))

if not found:
    print("No matching files found.")
else:
    for path, size in sorted(found, key=lambda item: str(item[0])):
        print(f"{path} | {size:,} bytes")

print("\nTotal matching files:", len(found))
print("STEP 46 COMPLETE — READ-ONLY SEARCH")

Searching for RippleWatch evidence and backups...

/content/ripplewatch_ai_v2/data/evidence.csv | 219 bytes
/content/ripplewatch_ai_v2/data/evidence_with_sources.csv | 17,256 bytes

Total matching files: 2
STEP 46 COMPLETE — READ-ONLY SEARCH

In [ ]:

from pathlib import Path
import pandas as pd

source_path = Path(
    "/content/ripplewatch_ai_v2/data/evidence_with_sources.csv"
)

if not source_path.exists():
    raise FileNotFoundError(f"Source file not found: {source_path}")

df = pd.read_csv(source_path)

print("SOURCE FILE:", source_path.name)
print("Total rows:", len(df))
print("\nColumns:")
print(df.columns.tolist())

print("\n--- MISSING / EMPTY VALUES ---")
for col in df.columns:
    empty_count = (
        df[col].isna()
        | df[col].astype("string").str.strip().eq("")
    ).sum()
    print(f"{col}: {int(empty_count)} empty values")

print("\n--- SOURCE PREVIEW ---")
preview_cols = [
    c for c in [
        "candidate_id",
        "source_title",
        "source_url",
        "source_published_date",
        "evidence_sentence",
        "evidence_text",
        "fetched_text",
        "review_status",
    ]
    if c in df.columns
]

print(df[preview_cols].head(3).to_string(index=False))

print("\n--- POSSIBLE EVIDENCE TEXT COLUMNS ---")
for col in df.columns:
    if any(term in col.lower() for term in [
        "evidence", "excerpt", "content", "body", "text"
    ]):
        nonempty = (
            df[col].notna()
            & df[col].astype("string").str.strip().ne("")
        ).sum()
        print(f"{col}: {int(nonempty)} non-empty rows")

print("\nSTEP 47 COMPLETE — INSPECTION ONLY")

SOURCE FILE: evidence_with_sources.csv
Total rows: 15

Columns:
['candidate_id', 'source_title', 'source_url', 'source_published_date', 'evidence_sentence', 'review_status', 'relevant_keywords', 'evidence_type', 'supplier_specific_alert_allowed', 'keep_for_review', 'signal_class', 'clean_evidence_sentence', 'dedup_key', 'duplicate_text', 'source_url_clean', 'verified_source_title', 'verified_source_url', 'verified_published_date', 'verified_fetch_status']

--- MISSING / EMPTY VALUES ---
candidate_id: 0 empty values
source_title: 0 empty values
source_url: 0 empty values
source_published_date: 0 empty values
evidence_sentence: 0 empty values
review_status: 0 empty values
relevant_keywords: 0 empty values
evidence_type: 0 empty values
supplier_specific_alert_allowed: 0 empty values
keep_for_review: 0 empty values
signal_class: 0 empty values
clean_evidence_sentence: 0 empty values
dedup_key: 0 empty values
duplicate_text: 0 empty values
source_url_clean: 0 empty values
verified_source_title: 0 empty values
verified_source_url: 0 empty values
verified_published_date: 0 empty values
verified_fetch_status: 0 empty values

--- SOURCE PREVIEW ---
candidate_id                                                 source_title                                                                                                source_url source_published_date                                                                                                                                                                                                                  evidence_sentence  review_status
        E001 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/            2026-09-22                An article from # Electronics manufacturers fret over extreme heat disruptions High temperatures are delaying supplier deliveries and hobbling productivity in the process, per the Global Electronics Association. pending_review
        E003 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/            2026-09-22                                                                            A Global Electronics Association survey found that two-fifths of manufacturers globally reported extreme heat-related supply chain disruptions in 2026. pending_review
        E006 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/            2026-09-22 Electronics manufacturers worldwide reported extreme heat-related supply chain disruptions this year, with supplier delivery delays cited as the most severe impacts, an industry trade association survey released Tuesday found. pending_review

--- POSSIBLE EVIDENCE TEXT COLUMNS ---
evidence_sentence: 15 non-empty rows
evidence_type: 15 non-empty rows
clean_evidence_sentence: 15 non-empty rows
duplicate_text: 15 non-empty rows

STEP 47 COMPLETE — INSPECTION ONLY

In [ ]:

from pathlib import Path
import pandas as pd

data_dir = Path("/content/ripplewatch_ai_v2/data")
source_path = data_dir / "evidence_with_sources.csv"
target_path = data_dir / "evidence.csv"

src = pd.read_csv(source_path)
target = pd.read_csv(target_path)

print("1. CURRENT TARGET SCHEMA")
print(target.columns.tolist())
print("Current evidence.csv rows:", len(target))

print("\n2. REVIEW STATUS COUNTS")
print(src["review_status"].value_counts(dropna=False).to_string())

print("\n3. VERIFIED FETCH STATUS COUNTS")
print(src["verified_fetch_status"].value_counts(dropna=False).to_string())

print("\n4. SUPPLIER-SPECIFIC ALERT PERMISSIONS")
print(
    src["supplier_specific_alert_allowed"]
    .astype(str)
    .value_counts(dropna=False)
    .to_string()
)

print("\n5. UNIQUE SOURCE / EVIDENCE COUNTS")
print("Unique candidate IDs:", src["candidate_id"].nunique())
print("Unique source URLs (clean):", src["source_url_clean"].nunique())
print("Duplicate evidence sentences:", int(
    src["clean_evidence_sentence"].duplicated(keep=False).sum()
))

print("\n6. SOURCE ROW SUMMARY")
cols = [
    "candidate_id",
    "verified_source_title",
    "verified_source_url",
    "verified_published_date",
    "verified_fetch_status",
    "review_status",
    "signal_class",
    "keep_for_review",
]
cols = [c for c in cols if c in src.columns]
print(src[cols].to_string(index=False))

print("\n7. TARGET COLUMN MAPPING CHECK")
for col in target.columns:
    print(f"{col}: {'AVAILABLE' if col in src.columns else 'NEEDS MAPPING'}")

print("\nSTEP 48 COMPLETE — READ-ONLY COMPATIBILITY CHECK")

1. CURRENT TARGET SCHEMA
['evidence_id', 'source_title', 'source_url', 'source_published_date', 'fetched_at', 'evidence_sentence', 'event_type', 'matched_supplier_names', 'matched_product_names', 'source_date_status', 'review_status', 'risk_score', 'supplier_specific_alert_allowed']
Current evidence.csv rows: 0

2. REVIEW STATUS COUNTS
review_status
pending_review    15

3. VERIFIED FETCH STATUS COUNTS
verified_fetch_status
fetched    15

4. SUPPLIER-SPECIFIC ALERT PERMISSIONS
supplier_specific_alert_allowed
False    15

5. UNIQUE SOURCE / EVIDENCE COUNTS
Unique candidate IDs: 15
Unique source URLs (clean): 1
Duplicate evidence sentences: 0

6. SOURCE ROW SUMMARY
candidate_id                                        verified_source_title                                                                                       verified_source_url verified_published_date verified_fetch_status  review_status             signal_class  keep_for_review
        E001 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              2026-09-22               fetched pending_review reported_industry_signal             True
        E003 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              2026-09-22               fetched pending_review reported_industry_signal             True
        E006 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              2026-09-22               fetched pending_review reported_industry_signal             True
        E007 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              2026-09-22               fetched pending_review reported_industry_signal             True
        E008 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              2026-09-22               fetched pending_review   context_or_uncertainty             True
        E009 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              2026-09-22               fetched pending_review   context_or_uncertainty             True
        E010 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              2026-09-22               fetched pending_review   context_or_uncertainty             True
        E011 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              2026-09-22               fetched pending_review reported_industry_signal             True
        E012 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              2026-09-22               fetched pending_review reported_industry_signal             True
        E013 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              2026-09-22               fetched pending_review reported_industry_signal             True
        E016 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              2026-09-22               fetched pending_review    potential_future_risk             True
        E017 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              2026-09-22               fetched pending_review    potential_future_risk             True
        E018 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              2026-09-22               fetched pending_review reported_industry_signal             True
        E019 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              2026-09-22               fetched pending_review reported_industry_signal             True
        E021 Electronics manufacturers fret over extreme heat disruptions https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/              2026-09-22               fetched pending_review    potential_future_risk             True

7. TARGET COLUMN MAPPING CHECK
evidence_id: NEEDS MAPPING
source_title: AVAILABLE
source_url: AVAILABLE
source_published_date: AVAILABLE
fetched_at: NEEDS MAPPING
evidence_sentence: AVAILABLE
event_type: NEEDS MAPPING
matched_supplier_names: NEEDS MAPPING
matched_product_names: NEEDS MAPPING
source_date_status: NEEDS MAPPING
review_status: AVAILABLE
risk_score: NEEDS MAPPING
supplier_specific_alert_allowed: AVAILABLE

STEP 48 COMPLETE — READ-ONLY COMPATIBILITY CHECK

In [ ]:

from pathlib import Path
from datetime import datetime, timezone
import pandas as pd
import shutil

data_dir = Path("/content/ripplewatch_ai_v2/data")
source_path = data_dir / "evidence_with_sources.csv"
target_path = data_dir / "evidence.csv"

if not source_path.exists():
    raise FileNotFoundError(f"Missing source file: {source_path}")

src = pd.read_csv(source_path).fillna("")

# Safety check: do not overwrite an already populated target.
if target_path.exists():
    current = pd.read_csv(target_path)
    if len(current) > 0:
        raise RuntimeError(
            f"STOP: {target_path.name} already has {len(current)} rows. "
            "No file was changed."
        )

# Create a timestamped backup of the current target, if it exists.
if target_path.exists():
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = data_dir / f"evidence_empty_backup_{stamp}.csv"
    shutil.copy2(target_path, backup_path)
    print("Previous target backed up to:", backup_path)

now = datetime.now(timezone.utc).isoformat()

def clean_url(row):
    value = str(row.get("verified_source_url", "")).strip()
    if not value:
        value = str(row.get("source_url_clean", "")).strip()
    if not value:
        value = str(row.get("source_url", "")).strip()

    # Convert Markdown [label](URL) into the plain URL.
    if value.startswith("[") and "](" in value and value.endswith(")"):
        value = value.split("](", 1)[1][:-1].strip()

    return value

records = []

for _, row in src.iterrows():
    title = str(row.get("verified_source_title", "")).strip()
    if not title:
        title = str(row.get("source_title", "")).strip()

    published = str(row.get("verified_published_date", "")).strip()
    if not published:
        published = str(row.get("source_published_date", "")).strip()

    sentence = str(row.get("clean_evidence_sentence", "")).strip()
    if not sentence:
        sentence = str(row.get("evidence_sentence", "")).strip()

    records.append({
        "evidence_id": str(row.get("candidate_id", "")).strip(),
        "source_title": title,
        "source_url": clean_url(row),
        "source_published_date": published,
        "fetched_at": now,
        "evidence_sentence": sentence,
        "event_type": str(row.get("signal_class", "")).strip(),
        "matched_supplier_names": "",
        "matched_product_names": "",
        "source_date_status": "UNVERIFIED",
        "review_status": "pending_review",
        "risk_score": "",
        "supplier_specific_alert_allowed": False,
    })

rebuilt = pd.DataFrame(records, columns=[
    "evidence_id",
    "source_title",
    "source_url",
    "source_published_date",
    "fetched_at",
    "evidence_sentence",
    "event_type",
    "matched_supplier_names",
    "matched_product_names",
    "source_date_status",
    "review_status",
    "risk_score",
    "supplier_specific_alert_allowed",
])

# Validate before writing.
assert len(rebuilt) == len(src), "Row count mismatch"
assert rebuilt["evidence_id"].is_unique, "Duplicate evidence IDs detected"
assert rebuilt["evidence_sentence"].str.strip().ne("").all(), \
    "One or more evidence sentences are empty"
assert not rebuilt["supplier_specific_alert_allowed"].any(), \
    "Supplier-specific alerts must remain disabled"

rebuilt.to_csv(target_path, index=False)

# Read back the saved file to verify the result.
check = pd.read_csv(target_path)

print("REBUILD COMPLETE")
print("Rows saved:", len(check))
print("Unique evidence IDs:", check["evidence_id"].nunique())
print("Empty evidence sentences:", int(
    check["evidence_sentence"].fillna("").str.strip().eq("").sum()
))
print("Supplier-specific alerts enabled:", int(
    check["supplier_specific_alert_allowed"].astype(str).str.lower().eq("true").sum()
))
print("Review status counts:")
print(check["review_status"].value_counts(dropna=False).to_string())
print("Saved file:", target_path)
print("\nSTEP 49 COMPLETE")

Previous target backed up to: /content/ripplewatch_ai_v2/data/evidence_empty_backup_20261025_041109.csv
REBUILD COMPLETE
Rows saved: 15
Unique evidence IDs: 15
Empty evidence sentences: 0
Supplier-specific alerts enabled: 0
Review status counts:
review_status
pending_review    15
Saved file: /content/ripplewatch_ai_v2/data/evidence.csv

STEP 49 COMPLETE

In [ ]:

from pathlib import Path
import pandas as pd

root = Path("/content/ripplewatch_ai_v2")
data_dir = root / "data"

evidence_path = data_dir / "evidence.csv"
app_path = root / "app.py"

df = pd.read_csv(evidence_path)

required_columns = [
    "evidence_id",
    "source_title",
    "source_url",
    "source_published_date",
    "fetched_at",
    "evidence_sentence",
    "event_type",
    "matched_supplier_names",
    "matched_product_names",
    "source_date_status",
    "review_status",
    "risk_score",
    "supplier_specific_alert_allowed",
]

print("1. REQUIRED SCHEMA")
missing = [c for c in required_columns if c not in df.columns]
print("Missing columns:", missing if missing else "None")
print("Column count:", len(df.columns))

print("\n2. DATA QUALITY")
print("Rows:", len(df))
print("Unique IDs:", df["evidence_id"].nunique())
print("Empty titles:", int(df["source_title"].fillna("").str.strip().eq("").sum()))
print("Empty URLs:", int(df["source_url"].fillna("").str.strip().eq("").sum()))
print("Empty evidence sentences:", int(
    df["evidence_sentence"].fillna("").str.strip().eq("").sum()
))
print("Markdown-formatted URLs:", int(
    df["source_url"].fillna("").str.startswith("[").sum()
))

print("\n3. SAFETY CHECKS")
print("Review statuses:")
print(df["review_status"].value_counts(dropna=False).to_string())
print("Supplier-specific alerts enabled:", int(
    df["supplier_specific_alert_allowed"]
    .astype(str).str.strip().str.lower().isin(["true", "1", "yes"]).sum()
))

print("\n4. DASHBOARD FILE")
print("app.py exists:", app_path.exists())

if app_path.exists():
    app_text = app_path.read_text(encoding="utf-8", errors="replace")
    print("References evidence.csv:", "evidence.csv" in app_text)
    print("References live_evidence.csv:", "live_evidence.csv" in app_text)

print("\nSTEP 50 COMPLETE — READ-ONLY VALIDATION")

1. REQUIRED SCHEMA
Missing columns: None
Column count: 13

2. DATA QUALITY
Rows: 15
Unique IDs: 15
Empty titles: 0
Empty URLs: 0
Empty evidence sentences: 0
Markdown-formatted URLs: 0

3. SAFETY CHECKS
Review statuses:
review_status
pending_review    15
Supplier-specific alerts enabled: 0

4. DASHBOARD FILE
app.py exists: True
References evidence.csv: False
References live_evidence.csv: False

STEP 50 COMPLETE — READ-ONLY VALIDATION

In [ ]:

from pathlib import Path
import re

app_path = Path("/content/ripplewatch_ai_v2/app.py")
code = app_path.read_text(encoding="utf-8", errors="replace")
lines = code.splitlines()

patterns = re.compile(
    r"read_csv|read_parquet|load_data|\.csv|data_dir|DATA_DIR|"
    r"Path\(|__file__|glob\(|rglob\(|live_evidence|evidence",
    re.IGNORECASE
)

matches = [
    (i, line.strip())
    for i, line in enumerate(lines, start=1)
    if patterns.search(line)
]

print("APP FILE:", app_path)
print("Total lines:", len(lines))
print("Matching lines:", len(matches))

for line_no, line in matches:
    print(f"{line_no}: {line[:240]}")

print("\n--- APP STARTUP / MAIN SECTION ---")
for i, line in enumerate(lines, start=1):
    if re.search(r"if __name__|st\.set_page_config|def main\(", line):
        start = max(1, i - 3)
        end = min(len(lines), i + 12)
        print(f"\nLines {start}-{end}:")
        for j in range(start, end + 1):
            print(f"{j}: {lines[j-1][:240]}")

print("\nSTEP 51 COMPLETE — READ-ONLY INSPECTION")

APP FILE: /content/ripplewatch_ai_v2/app.py
Total lines: 160
Matching lines: 9
6: PROJECT_DIR = Path("/content/ripplewatch_ai_v2")
7: DATA_DIR = PROJECT_DIR / "data"
8: DATA_FILE = DATA_DIR / "dashboard_evidence_summary.csv"
20: "Preliminary industry-level evidence only. "
29: df = pd.read_csv(DATA_FILE)
80: c1.metric("Evidence records", len(filtered))
87: int((filtered["review_status_final"] == "manual_evidence_review").sum())
108: st.subheader("Evidence records")
157: "Prototype dashboard. Evidence requires manual verification. "

--- APP STARTUP / MAIN SECTION ---

Lines 7-22:
7: DATA_DIR = PROJECT_DIR / "data"
8: DATA_FILE = DATA_DIR / "dashboard_evidence_summary.csv"
9:
10: st.set_page_config(
11:     page_title="RippleWatch AI",
12:     page_icon="🌊",
13:     layout="wide"
14: )
15:
16: st.title("🌊 RippleWatch AI")
17: st.caption("Supply-chain risk intelligence | Industry-level signals")
18:
19: st.warning(
20:     "Preliminary industry-level evidence only. "
21:     "Scores are heuristic indicators, not calibrated probabilities. "
22:     "No supplier-specific alerts are currently authorized."

STEP 51 COMPLETE — READ-ONLY INSPECTION

In [ ]:

from pathlib import Path
import pandas as pd

root = Path("/content/ripplewatch_ai_v2")
data_dir = root / "data"
summary_path = data_dir / "dashboard_evidence_summary.csv"
app_path = root / "app.py"

print("1. DASHBOARD INPUT FILE")
print("Exists:", summary_path.exists())

if summary_path.exists():
    summary = pd.read_csv(summary_path)
    print("Rows:", len(summary))
    print("Columns:", summary.columns.tolist())

    print("\n2. EMPTY VALUES")
    for col in summary.columns:
        empty = (
            summary[col].isna()
            | summary[col].astype("string").str.strip().eq("")
        ).sum()
        print(f"{col}: {int(empty)}")

    print("\n3. CURRENT DASHBOARD DATA PREVIEW")
    print(summary.head(5).to_string(index=False))
else:
    summary = None
    print("Summary CSV is missing.")

print("\n4. FIELDS REFERENCED BY APP")
lines = app_path.read_text(encoding="utf-8", errors="replace").splitlines()

for start, end in [(24, 60), (60, 110), (110, 160)]:
    print(f"\n--- app.py lines {start}-{min(end, len(lines))} ---")
    for i in range(start, min(end, len(lines)) + 1):
        print(f"{i}: {lines[i-1]}")

print("\nSTEP 52 COMPLETE — READ-ONLY INSPECTION")

1. DASHBOARD INPUT FILE
Exists: True
Rows: 15
Columns: ['candidate_id', 'verified_source_title', 'verified_published_date', 'signal_class', 'industry_risk_score_v2', 'score_reason_v2', 'review_status_final', 'risk_scope', 'supplier_specific_alert_allowed', 'source_url']

2. EMPTY VALUES
candidate_id: 0
verified_source_title: 0
verified_published_date: 0
signal_class: 0
industry_risk_score_v2: 0
score_reason_v2: 0
review_status_final: 0
risk_scope: 0
supplier_specific_alert_allowed: 0
source_url: 0

3. CURRENT DASHBOARD DATA PREVIEW
candidate_id                                        verified_source_title verified_published_date             signal_class  industry_risk_score_v2                                                                                   score_reason_v2    review_status_final          risk_scope  supplier_specific_alert_allowed                                                                                                source_url
        E001 Electronics manufacturers fret over extreme heat disruptions              2026-09-22 reported_industry_signal                      20                                                 reported_supplier_delivery_or_productivity_impact manual_evidence_review industry_level_only                            False https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/
        E003 Electronics manufacturers fret over extreme heat disruptions              2026-09-22 reported_industry_signal                      20                                       reported_disruption_or_exposure;survey_prevalence_statistic manual_evidence_review industry_level_only                            False https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/
        E006 Electronics manufacturers fret over extreme heat disruptions              2026-09-22 reported_industry_signal                      20                                                 reported_supplier_delivery_or_productivity_impact manual_evidence_review industry_level_only                            False https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/
        E007 Electronics manufacturers fret over extreme heat disruptions              2026-09-22 reported_industry_signal                      30 reported_disruption_or_exposure;reported_supply_or_operational_impact;survey_prevalence_statistic manual_evidence_review industry_level_only                            False https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/
        E008 Electronics manufacturers fret over extreme heat disruptions              2026-09-22   context_or_uncertainty                       0                                                                       context_or_uncertainty_only manual_evidence_review industry_level_only                            False https://www.supplychaindive.com/news/electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/

4. FIELDS REFERENCED BY APP

--- app.py lines 24-60 ---
24:
25: if not DATA_FILE.exists():
26:     st.error(f"Dashboard data file not found: {DATA_FILE}")
27:     st.stop()
28:
29: df = pd.read_csv(DATA_FILE)
30:
31: required_columns = [
32:     "candidate_id",
33:     "verified_source_title",
34:     "verified_published_date",
35:     "signal_class",
36:     "industry_risk_score_v2",
37:     "score_reason_v2",
38:     "review_status_final",
39:     "risk_scope",
40:     "supplier_specific_alert_allowed"
41: ]
42:
43: missing = [col for col in required_columns if col not in df.columns]
44: if missing:
45:     st.error(f"Required columns are missing: {missing}")
46:     st.stop()
47:
48: df["industry_risk_score_v2"] = pd.to_numeric(
49:     df["industry_risk_score_v2"], errors="coerce"
50: )
51: df["verified_published_date"] = pd.to_datetime(
52:     df["verified_published_date"], errors="coerce"
53: )
54:
55: # Sidebar filters
56: st.sidebar.header("Filters")
57:
58: signal_options = sorted(df["signal_class"].dropna().unique().tolist())
59: selected_signals = st.sidebar.multiselect(
60:     "Signal classification",

--- app.py lines 60-110 ---
60:     "Signal classification",
61:     options=signal_options,
62:     default=signal_options
63: )
64:
65: min_score = st.sidebar.slider(
66:     "Minimum preliminary score",
67:     min_value=0,
68:     max_value=100,
69:     value=0,
70:     step=5
71: )
72:
73: filtered = df[
74:     df["signal_class"].isin(selected_signals)
75:     & (df["industry_risk_score_v2"] >= min_score)
76: ].copy()
77:
78: # Summary metrics
79: c1, c2, c3, c4 = st.columns(4)
80: c1.metric("Evidence records", len(filtered))
81: c2.metric(
82:     "Reported industry signals",
83:     int((filtered["signal_class"] == "reported_industry_signal").sum())
84: )
85: c3.metric(
86:     "Needs manual review",
87:     int((filtered["review_status_final"] == "manual_evidence_review").sum())
88: )
89: c4.metric(
90:     "Supplier alerts allowed",
91:     int(
92:         filtered["supplier_specific_alert_allowed"]
93:         .fillna(False).astype(bool).sum()
94:     )
95: )
96:
97: st.subheader("Industry signal score distribution")
98: score_counts = (
99:     filtered["industry_risk_score_v2"]
100:     .value_counts()
101:     .sort_index()
102: )
103: if not score_counts.empty:
104:     st.bar_chart(score_counts)
105: else:
106:     st.info("No records match the selected filters.")
107:
108: st.subheader("Evidence records")
109:
110: display_columns = [

--- app.py lines 110-160 ---
110: display_columns = [
111:     "candidate_id",
112:     "verified_source_title",
113:     "verified_published_date",
114:     "signal_class",
115:     "industry_risk_score_v2",
116:     "score_reason_v2",
117:     "review_status_final",
118:     "risk_scope",
119:     "supplier_specific_alert_allowed"
120: ]
121:
122: st.dataframe(
123:     filtered[display_columns],
124:     use_container_width=True,
125:     hide_index=True
126: )
127:
128: st.subheader("Source details")
129: for _, row in filtered.iterrows():
130:     with st.expander(
131:         f"{row['candidate_id']} · {row['verified_source_title']}"
132:     ):
133:         st.write("Publication date:", (
134:             str(row["verified_published_date"].date())
135:             if pd.notna(row["verified_published_date"])
136:             else "Unknown"
137:         ))
138:
139:         article_url = (
140:             "https://www.supplychaindive.com/news/"
141:             "electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/"
142:         )
143:         st.link_button("Open original article", article_url)
144:
145:         st.write("Signal classification:", row["signal_class"])
146:         st.write("Preliminary score:", row["industry_risk_score_v2"])
147:         st.write("Scoring explanation:", row["score_reason_v2"])
148:         st.write("Review status:", row["review_status_final"])
149:         st.write("Risk scope:", row["risk_scope"])
150:         st.write(
151:             "Supplier-specific alert allowed:",
152:             bool(row["supplier_specific_alert_allowed"])
153:         )
154:
155: st.divider()
156: st.caption(
157:     "Prototype dashboard. Evidence requires manual verification. "
158:     "Industry-level reports must not be presented as confirmed risks "
159:     "to a named supplier or product."
160: )

STEP 52 COMPLETE — READ-ONLY INSPECTION

In [ ]:

from pathlib import Path
import pandas as pd

root = Path("/content/ripplewatch_ai_v2")
path = root / "data" / "dashboard_evidence_summary.csv"

df = pd.read_csv(path)

print("1. RECORD COUNTS")
print("Total records:", len(df))
print("Unique candidate IDs:", df["candidate_id"].nunique())
print("Unique source titles:", df["verified_source_title"].nunique())
print("Unique source URLs (after cleaning):",
      df["source_url"].astype(str).str.extract(r"(https?://[^)\]]+)")[0].nunique())

print("\n2. SCORE DISTRIBUTION")
print(df["industry_risk_score_v2"].value_counts().sort_index().to_string())

print("\n3. SIGNAL CLASSIFICATION")
print(df["signal_class"].value_counts(dropna=False).to_string())

print("\n4. REVIEW STATUS")
print(df["review_status_final"].value_counts(dropna=False).to_string())

print("\n5. SUPPLIER ALERT PERMISSIONS")
print(df["supplier_specific_alert_allowed"].value_counts(dropna=False).to_string())

print("\n6. URL FORMAT CHECK")
urls = df["source_url"].astype(str)
markdown_urls = urls.str.match(r"^\[https?://.*\]\(https?://.*\)$")
print("Markdown-formatted URLs:", int(markdown_urls.sum()))
print("Plain HTTP(S) URLs:", int(urls.str.match(r"^https?://").sum()))

print("\n7. SCORE VALIDATION")
scores = pd.to_numeric(df["industry_risk_score_v2"], errors="coerce")
print("Missing/non-numeric scores:", int(scores.isna().sum()))
print("Scores outside 0–100:", int((~scores.between(0, 100)).sum()))

print("\nSTEP 53 COMPLETE — READ-ONLY CHECK")

1. RECORD COUNTS
Total records: 15
Unique candidate IDs: 15
Unique source titles: 1
Unique source URLs (after cleaning): 1

2. SCORE DISTRIBUTION
industry_risk_score_v2
0     3
10    2
20    8
30    2

3. SIGNAL CLASSIFICATION
signal_class
reported_industry_signal    9
context_or_uncertainty      3
potential_future_risk       3

4. REVIEW STATUS
review_status_final
manual_evidence_review    15

5. SUPPLIER ALERT PERMISSIONS
supplier_specific_alert_allowed
False    15

6. URL FORMAT CHECK
Markdown-formatted URLs: 0
Plain HTTP(S) URLs: 15

7. SCORE VALIDATION
Missing/non-numeric scores: 0
Scores outside 0–100: 0

STEP 53 COMPLETE — READ-ONLY CHECK

In [ ]:

from pathlib import Path
import pandas as pd

data_dir = Path("/content/ripplewatch_ai_v2/data")

evidence_path = data_dir / "evidence.csv"
summary_path = data_dir / "dashboard_evidence_summary.csv"

evidence = pd.read_csv(evidence_path)
summary = pd.read_csv(summary_path)

print("1. EVIDENCE SENTENCES")
print("Non-empty evidence sentences:",
      int(evidence["evidence_sentence"].fillna("").astype(str).str.strip().ne("").sum()),
      "of", len(evidence))

print("\n2. CANDIDATE ID MATCH")
evidence_ids = set(evidence["evidence_id"].astype(str))
summary_ids = set(summary["candidate_id"].astype(str))

print("IDs in evidence.csv:", len(evidence_ids))
print("IDs in dashboard summary:", len(summary_ids))
print("IDs only in evidence.csv:", sorted(evidence_ids - summary_ids))
print("IDs only in dashboard summary:", sorted(summary_ids - evidence_ids))

print("\n3. EVIDENCE PREVIEW")
cols = [
    "evidence_id",
    "source_title",
    "evidence_sentence",
    "event_type",
    "review_status"
]
print(evidence[cols].head(5).to_string(index=False))

print("\nSTEP 54 COMPLETE — READ-ONLY INSPECTION")

1. EVIDENCE SENTENCES
Non-empty evidence sentences: 15 of 15

2. CANDIDATE ID MATCH
IDs in evidence.csv: 15
IDs in dashboard summary: 15
IDs only in evidence.csv: []
IDs only in dashboard summary: []

3. EVIDENCE PREVIEW
evidence_id                                                 source_title                                                                                                                                                                                                                  evidence_sentence               event_type  review_status
       E001 Electronics manufacturers fret over extreme heat disruptions                                                                                               High temperatures are delaying supplier deliveries and hobbling productivity in the process, per the Global Electronics Association. reported_industry_signal pending_review
       E003 Electronics manufacturers fret over extreme heat disruptions                                                                            A Global Electronics Association survey found that two-fifths of manufacturers globally reported extreme heat-related supply chain disruptions in 2026. reported_industry_signal pending_review
       E006 Electronics manufacturers fret over extreme heat disruptions Electronics manufacturers worldwide reported extreme heat-related supply chain disruptions this year, with supplier delivery delays cited as the most severe impacts, an industry trade association survey released Tuesday found. reported_industry_signal pending_review
       E007 Electronics manufacturers fret over extreme heat disruptions                Almost half of manufacturers surveyed by the Global Electronics Association said supplier fulfillment was most affected, with 50% of manufacturers in North America, Europe and Asia Pacific reporting disruptions. reported_industry_signal pending_review
       E008 Electronics manufacturers fret over extreme heat disruptions                                                                                                                                                                     The survey did not ask for the exact types of supplier delays.   context_or_uncertainty pending_review

STEP 54 COMPLETE — READ-ONLY INSPECTION

In [ ]:

from pathlib import Path
import pandas as pd

path = Path("/content/ripplewatch_ai_v2/data/evidence.csv")
df = pd.read_csv(path)

text_col = df["evidence_sentence"].fillna("").astype(str).str.strip()
normalized = text_col.str.lower().str.replace(r"\s+", " ", regex=True)

print("1. EXACT DUPLICATES")
print("Duplicate evidence sentences:",
      int(normalized.duplicated(keep=False).sum()))
print("Unique evidence sentences:", int(normalized.nunique()))

print("\n2. SENTENCE LENGTH")
lengths = text_col.str.split().str.len()
print("Shortest sentence (words):", int(lengths.min()))
print("Longest sentence (words):", int(lengths.max()))
print("Sentences under 8 words:", int((lengths < 8).sum()))

print("\n3. EVIDENCE BY EVENT TYPE")
print(df.groupby("event_type")["evidence_id"].count().to_string())

print("\n4. REVIEW STATUS")
print(df["review_status"].value_counts(dropna=False).to_string())

print("\n5. EVIDENCE SENTENCES FOR MANUAL REVIEW")
for _, row in df.iterrows():
    print(f"\n{row['evidence_id']} | {row['event_type']}")
    print(row["evidence_sentence"])

print("\nSTEP 55 COMPLETE — READ-ONLY QUALITY CHECK")

1. EXACT DUPLICATES
Duplicate evidence sentences: 0
Unique evidence sentences: 15

2. SENTENCE LENGTH
Shortest sentence (words): 12
Longest sentence (words): 59
Sentences under 8 words: 0

3. EVIDENCE BY EVENT TYPE
event_type
context_or_uncertainty      3
potential_future_risk       3
reported_industry_signal    9

4. REVIEW STATUS
review_status
pending_review    15

5. EVIDENCE SENTENCES FOR MANUAL REVIEW

E001 | reported_industry_signal
High temperatures are delaying supplier deliveries and hobbling productivity in the process, per the Global Electronics Association.

E003 | reported_industry_signal
A Global Electronics Association survey found that two-fifths of manufacturers globally reported extreme heat-related supply chain disruptions in 2026.

E006 | reported_industry_signal
Electronics manufacturers worldwide reported extreme heat-related supply chain disruptions this year, with supplier delivery delays cited as the most severe impacts, an industry trade association survey released Tuesday found.

E007 | reported_industry_signal
Almost half of manufacturers surveyed by the Global Electronics Association said supplier fulfillment was most affected, with 50% of manufacturers in North America, Europe and Asia Pacific reporting disruptions.

E008 | context_or_uncertainty
The survey did not ask for the exact types of supplier delays.

E009 | context_or_uncertainty
However, Chief Economist Shawn DuBravac told Supply Chain Dive there were likely multiple causes, such as labor issues, supplier factory constraints and freight and warehouse bottlenecks.

E010 | context_or_uncertainty
“My sense is that it was probably an assortment of different things that would fall under that broader category of supplier delays,” DuBravac said.

E011 | reported_industry_signal
Two-fifths of manufacturers globally reported some type of heat-related supply chain disruption.

E012 | reported_industry_signal
In North America, minor or no disruptions were most common, at 20% and 57% of respondents, respectively, while moderate and major interruptions were each cited by 6%. North American electronic supply chains face extreme heat-related impacts The percentage of specific disruptions faced by electronics manufacturers in the region who reported impacts from extreme heat on their operations in 2026.

E013 | reported_industry_signal
More than four-fifths of manufacturers worldwide who experienced heat-related disruptions reported negative impacts on productivity and operational throughput, per the survey.

E016 | potential_future_risk
North American firms that had not experienced heat-related disruptions are still anxious about potential issues.The most cited anticipated bottlenecks were operating constraints, including cooling limits, and power reliability issues, including curtailments, at 29% each, the survey found.

E017 | potential_future_risk
Other potential disruptions included transportation delays, unplanned equipment downtime and supplier delivery delays, with 17% of North American firms citing these.

E018 | reported_industry_signal
Single-digit percentages cited customer demand disruptions, missed shifts, reduced staffing and product quality defects.

E019 | reported_industry_signal
More than half of manufacturers globally said their supply chains were exposed to severe heat-related disruptions.

E021 | potential_future_risk
Looking ahead, more than two-thirds of manufacturers worldwide expected extreme heat-driven interruptions in productivity or operational throughput in the coming years, the survey found.

STEP 55 COMPLETE — READ-ONLY QUALITY CHECK

In [ ]:

from pathlib import Path
import pandas as pd

path = Path("/content/ripplewatch_ai_v2/data/evidence_with_sources.csv")
df = pd.read_csv(path)

print("Available columns:", df.columns.tolist())

for candidate_id in ["E012", "E016"]:
    row = df[df["candidate_id"].astype(str) == candidate_id]

    print(f"\n{'=' * 18} {candidate_id} {'=' * 18}")

    if row.empty:
        print("Candidate not found.")
        continue

    for col in [
        "source_title",
        "evidence_sentence",
        "clean_evidence_sentence",
        "duplicate_text",
        "relevant_keywords",
        "evidence_type"
    ]:
        if col in df.columns:
            print(f"\n{col}:")
            print(row.iloc[0][col])

print("\nSTEP 56 COMPLETE — ORIGINAL TEXT INSPECTED")

Available columns: ['candidate_id', 'source_title', 'source_url', 'source_published_date', 'evidence_sentence', 'review_status', 'relevant_keywords', 'evidence_type', 'supplier_specific_alert_allowed', 'keep_for_review', 'signal_class', 'clean_evidence_sentence', 'dedup_key', 'duplicate_text', 'source_url_clean', 'verified_source_title', 'verified_source_url', 'verified_published_date', 'verified_fetch_status']

================== E012 ==================

source_title:
Electronics manufacturers fret over extreme heat disruptions

evidence_sentence:
In North America, minor or no disruptions were most common, at 20% and 57% of respondents, respectively, while moderate and major interruptions were each cited by 6%. #### North American electronic supply chains face extreme heat-related impacts The percentage of specific disruptions faced by electronics manufacturers in the region who reported impacts from extreme heat on their operations in 2026.

clean_evidence_sentence:
In North America, minor or no disruptions were most common, at 20% and 57% of respondents, respectively, while moderate and major interruptions were each cited by 6%. North American electronic supply chains face extreme heat-related impacts The percentage of specific disruptions faced by electronics manufacturers in the region who reported impacts from extreme heat on their operations in 2026.

duplicate_text:
False

relevant_keywords:
['supply chain', 'disruption', 'extreme heat']

evidence_type:
industry_signal

================== E016 ==================

source_title:
Electronics manufacturers fret over extreme heat disruptions

evidence_sentence:
North American firms that had not experienced heat-related disruptions are still anxious about potential issues.The most cited anticipated bottlenecks were operating constraints, including cooling limits, and power reliability issues, including curtailments, at 29% each, the survey found.

clean_evidence_sentence:
North American firms that had not experienced heat-related disruptions are still anxious about potential issues.The most cited anticipated bottlenecks were operating constraints, including cooling limits, and power reliability issues, including curtailments, at 29% each, the survey found.

duplicate_text:
False

relevant_keywords:
['disruption']

evidence_type:
industry_signal

STEP 56 COMPLETE — ORIGINAL TEXT INSPECTED

In [ ]:

from pathlib import Path

app_path = Path("/content/ripplewatch_ai_v2/app.py")
lines = app_path.read_text(encoding="utf-8").splitlines()

print("APP FILE:", app_path.exists())
print("\nEVIDENCE-RELATED REFERENCES")

terms = [
    "evidence_sentence",
    "clean_evidence_sentence",
    "source_url",
    "st.dataframe",
    "Source details",
    "display_columns"
]

for term in terms:
    matches = [
        (i, line.strip())
        for i, line in enumerate(lines, start=1)
        if term.lower() in line.lower()
    ]
    print(f"\n{term}:")
    if matches:
        for line_no, line in matches:
            print(f"  Line {line_no}: {line}")
    else:
        print("  No matches")

print("\nSTEP 57 COMPLETE — READ-ONLY APP CHECK")

APP FILE: True

EVIDENCE-RELATED REFERENCES

evidence_sentence:
  No matches

clean_evidence_sentence:
  No matches

source_url:
  No matches

st.dataframe:
  Line 122: st.dataframe(

Source details:
  Line 128: st.subheader("Source details")

display_columns:
  Line 110: display_columns = [
  Line 123: filtered[display_columns],

STEP 57 COMPLETE — READ-ONLY APP CHECK

In [ ]:

from pathlib import Path
import pandas as pd
import re

path = Path("/content/ripplewatch_ai_v2/data/evidence_with_sources.csv")
df = pd.read_csv(path)

print("SCANNING", len(df), "EVIDENCE RECORDS")

for _, row in df.iterrows():
    cid = row["candidate_id"]
    text = str(row.get("evidence_sentence", ""))
    issues = []

    if re.search(r"####|#{1,6}\s+", text):
        issues.append("possible Markdown heading")

    if re.search(r"\.\S[A-Z]", text):
        issues.append("possible missing sentence space")

    if re.search(
        r"\b(the percentage of|figure \d+|table \d+|chart \d+)\b",
        text,
        flags=re.IGNORECASE
    ):
        issues.append("possible chart/table caption")

    if re.search(r"\]\(https?://|https?://", text):
        issues.append("possible embedded URL")

    if issues:
        print(f"\n{cid}: {', '.join(issues)}")
        print(text)

print("\nSTEP 58 COMPLETE — READ-ONLY TEXT SCAN")

SCANNING 15 EVIDENCE RECORDS

E001: possible Markdown heading
An article from # Electronics manufacturers fret over extreme heat disruptions High temperatures are delaying supplier deliveries and hobbling productivity in the process, per the Global Electronics Association.

E012: possible Markdown heading, possible chart/table caption
In North America, minor or no disruptions were most common, at 20% and 57% of respondents, respectively, while moderate and major interruptions were each cited by 6%. #### North American electronic supply chains face extreme heat-related impacts The percentage of specific disruptions faced by electronics manufacturers in the region who reported impacts from extreme heat on their operations in 2026.

STEP 58 COMPLETE — READ-ONLY TEXT SCAN

In [ ]:

from pathlib import Path
import pandas as pd
import re

path = Path("/content/ripplewatch_ai_v2/data/evidence_with_sources.csv")
df = pd.read_csv(path)

for cid in ["E001", "E012", "E016"]:
    row = df[df["candidate_id"].astype(str) == cid]

    print(f"\n{'=' * 15} {cid} {'=' * 15}")
    if row.empty:
        print("Candidate not found")
        continue

    original = str(row.iloc[0]["evidence_sentence"]).strip()
    proposed = original
    note = "No automatic change proposed"

    if cid == "E001":
        proposed = re.sub(
            r"^An article from\s+#\s*Electronics manufacturers fret over extreme heat disruptions\s*",
            "",
            original,
            flags=re.IGNORECASE
        ).strip()
        note = "Remove article-heading prefix only"

    elif cid == "E012":
        proposed = re.split(
            r"\s*#{1,6}\s*North American electronic supply chains face extreme heat-related impacts",
            original,
            maxsplit=1
        )[0].strip()
        note = "Keep survey finding; caption remains preserved in original"

    elif cid == "E016":
        proposed = re.sub(r"issues\.(?=[A-Z])", "issues. ", original)
        note = "Insert missing space after sentence boundary"

    print("Original:")
    print(original)
    print("\nProposed evidence sentence:")
    print(proposed)
    print("\nNote:", note)
    print("Original unchanged: True")

print("\nSTEP 59 COMPLETE — PREVIEW ONLY")

=============== E001 ===============
Original:
An article from # Electronics manufacturers fret over extreme heat disruptions High temperatures are delaying supplier deliveries and hobbling productivity in the process, per the Global Electronics Association.

Proposed evidence sentence:
High temperatures are delaying supplier deliveries and hobbling productivity in the process, per the Global Electronics Association.

Note: Remove article-heading prefix only
Original unchanged: True

=============== E012 ===============
Original:
In North America, minor or no disruptions were most common, at 20% and 57% of respondents, respectively, while moderate and major interruptions were each cited by 6%. #### North American electronic supply chains face extreme heat-related impacts The percentage of specific disruptions faced by electronics manufacturers in the region who reported impacts from extreme heat on their operations in 2026.

Proposed evidence sentence:
In North America, minor or no disruptions were most common, at 20% and 57% of respondents, respectively, while moderate and major interruptions were each cited by 6%.

Note: Keep survey finding; caption remains preserved in original
Original unchanged: True

=============== E016 ===============
Original:
North American firms that had not experienced heat-related disruptions are still anxious about potential issues.The most cited anticipated bottlenecks were operating constraints, including cooling limits, and power reliability issues, including curtailments, at 29% each, the survey found.

Proposed evidence sentence:
North American firms that had not experienced heat-related disruptions are still anxious about potential issues. The most cited anticipated bottlenecks were operating constraints, including cooling limits, and power reliability issues, including curtailments, at 29% each, the survey found.

Note: Insert missing space after sentence boundary
Original unchanged: True

STEP 59 COMPLETE — PREVIEW ONLY

In [ ]:

from pathlib import Path
import pandas as pd
import re

data_dir = Path("/content/ripplewatch_ai_v2/data")
source_path = data_dir / "evidence_with_sources.csv"
output_path = data_dir / "evidence_text_cleanup_review_v1.csv"

df = pd.read_csv(source_path)

# Safety checks: don't overwrite an existing review file.
if output_path.exists():
    raise FileExistsError(
        f"{output_path} already exists. Nothing was overwritten."
    )

records = []

for _, row in df.iterrows():
    cid = str(row["candidate_id"])
    original = str(row["evidence_sentence"]).strip()
    proposed = original
    note = "No change proposed; manual review required"

    if cid == "E001":
        proposed = re.sub(
            r"^An article from\s+#\s*Electronics manufacturers fret over extreme heat disruptions\s*",
            "",
            original,
            flags=re.IGNORECASE
        ).strip()
        note = "Proposed removal of article-heading prefix"

    elif cid == "E012":
        proposed = re.split(
            r"\s*#{1,6}\s*North American electronic supply chains face extreme heat-related impacts",
            original,
            maxsplit=1
        )[0].strip()
        note = (
            "Proposed separation of survey finding from chart heading/caption; "
            "original retains the full text"
        )

    elif cid == "E016":
        proposed = re.sub(
            r"issues\.(?=[A-Z])",
            "issues. ",
            original
        )
        note = "Proposed insertion of missing sentence-boundary space"

    records.append({
        "candidate_id": cid,
        "original_evidence_sentence": original,
        "proposed_evidence_sentence": proposed,
        "cleanup_note": note,
        "review_status": "pending_review",
        "supplier_specific_alert_allowed": False
    })

review_df = pd.DataFrame(records)
review_df.to_csv(output_path, index=False)

# Validate the newly created review file.
check = pd.read_csv(output_path)

assert len(check) == len(df)
assert check["candidate_id"].is_unique
assert check["review_status"].eq("pending_review").all()
assert (~check["supplier_specific_alert_allowed"].astype(bool)).all()

print("STEP 60 COMPLETE")
print("New review file:", output_path)
print("Records:", len(check))
print("Changed proposals:",
      int((check["original_evidence_sentence"] !=
           check["proposed_evidence_sentence"]).sum()))
print("All records pending review:",
      check["review_status"].eq("pending_review").all())
print("Supplier alerts enabled:",
      int(check["supplier_specific_alert_allowed"].astype(bool).sum()))
print("Original source file modified: No")
print("Original evidence.csv modified: No")

STEP 60 COMPLETE
New review file: /content/ripplewatch_ai_v2/data/evidence_text_cleanup_review_v1.csv
Records: 15
Changed proposals: 3
All records pending review: True
Supplier alerts enabled: 0
Original source file modified: No
Original evidence.csv modified: No

In [ ]:

from pathlib import Path
import pandas as pd

data_dir = Path("/content/ripplewatch_ai_v2/data")

review = pd.read_csv(data_dir / "evidence_text_cleanup_review_v1.csv")
original = pd.read_csv(data_dir / "evidence_with_sources.csv")

print("1. RECORD COUNTS")
print("Review file:", len(review))
print("Original source:", len(original))

print("\n2. PROPOSED CHANGES")
changed = review[
    review["original_evidence_sentence"]
    != review["proposed_evidence_sentence"]
]

print("Changed records:", len(changed))
print(changed[[
    "candidate_id",
    "cleanup_note",
    "review_status",
    "supplier_specific_alert_allowed"
]].to_string(index=False))

print("\n3. UNCHANGED RECORDS")
unchanged = review[
    review["original_evidence_sentence"]
    == review["proposed_evidence_sentence"]
]
print("Unchanged records:", len(unchanged))

print("\n4. REVIEW SAFETY")
print("All pending:",
      review["review_status"].eq("pending_review").all())
print("Alerts enabled:",
      int(review["supplier_specific_alert_allowed"].astype(bool).sum()))

print("\n5. ORIGINAL TEXT PRESERVATION")
merged = review.merge(
    original[["candidate_id", "evidence_sentence"]],
    on="candidate_id",
    suffixes=("_review", "_source"),
    validate="one_to_one"
)
print("Original text matches source:",
      merged["original_evidence_sentence"].eq(
          merged["evidence_sentence"]
      ).all())

print("\nSTEP 61 COMPLETE — READ-ONLY VALIDATION")

1. RECORD COUNTS
Review file: 15
Original source: 15

2. PROPOSED CHANGES
Changed records: 3
candidate_id                                                                                     cleanup_note  review_status  supplier_specific_alert_allowed
        E001                                                       Proposed removal of article-heading prefix pending_review                            False
        E012 Proposed separation of survey finding from chart heading/caption; original retains the full text pending_review                            False
        E016                                            Proposed insertion of missing sentence-boundary space pending_review                            False

3. UNCHANGED RECORDS
Unchanged records: 12

4. REVIEW SAFETY
All pending: True
Alerts enabled: 0

5. ORIGINAL TEXT PRESERVATION
Original text matches source: True

STEP 61 COMPLETE — READ-ONLY VALIDATION

In [ ]:

from pathlib import Path
import pandas as pd

path = Path(
    "/content/ripplewatch_ai_v2/data/"
    "evidence_text_cleanup_review_v1.csv"
)
df = pd.read_csv(path)

for cid in ["E001", "E012", "E016"]:
    row = df.loc[df["candidate_id"] == cid].iloc[0]

    print(f"\n{'=' * 12} {cid} {'=' * 12}")
    print("\nORIGINAL TEXT:")
    print(row["original_evidence_sentence"])

    print("\nPROPOSED TEXT:")
    print(row["proposed_evidence_sentence"])

    print("\nREVIEW NOTE:")
    print(row["cleanup_note"])

    print("\nStatus:", row["review_status"])

print("\nSTEP 62 COMPLETE — FINAL TEXT REVIEW")

============ E001 ============

ORIGINAL TEXT:
An article from # Electronics manufacturers fret over extreme heat disruptions High temperatures are delaying supplier deliveries and hobbling productivity in the process, per the Global Electronics Association.

PROPOSED TEXT:
High temperatures are delaying supplier deliveries and hobbling productivity in the process, per the Global Electronics Association.

REVIEW NOTE:
Proposed removal of article-heading prefix

Status: pending_review

============ E012 ============

ORIGINAL TEXT:
In North America, minor or no disruptions were most common, at 20% and 57% of respondents, respectively, while moderate and major interruptions were each cited by 6%. #### North American electronic supply chains face extreme heat-related impacts The percentage of specific disruptions faced by electronics manufacturers in the region who reported impacts from extreme heat on their operations in 2026.

PROPOSED TEXT:
In North America, minor or no disruptions were most common, at 20% and 57% of respondents, respectively, while moderate and major interruptions were each cited by 6%.

REVIEW NOTE:
Proposed separation of survey finding from chart heading/caption; original retains the full text

Status: pending_review

============ E016 ============

ORIGINAL TEXT:
North American firms that had not experienced heat-related disruptions are still anxious about potential issues.The most cited anticipated bottlenecks were operating constraints, including cooling limits, and power reliability issues, including curtailments, at 29% each, the survey found.

PROPOSED TEXT:
North American firms that had not experienced heat-related disruptions are still anxious about potential issues. The most cited anticipated bottlenecks were operating constraints, including cooling limits, and power reliability issues, including curtailments, at 29% each, the survey found.

REVIEW NOTE:
Proposed insertion of missing sentence-boundary space

Status: pending_review

STEP 62 COMPLETE — FINAL TEXT REVIEW

In [ ]:

from pathlib import Path
import pandas as pd

data_dir = Path("/content/ripplewatch_ai_v2/data")
input_path = data_dir / "evidence_text_cleanup_review_v1.csv"
output_path = data_dir / "evidence_text_cleanup_decisions_v1.csv"

if output_path.exists():
    raise FileExistsError(
        f"{output_path} already exists. Nothing was overwritten."
    )

df = pd.read_csv(input_path)

decisions = {
    "E001": (
        "ACCEPT_TEXT_CLEANUP",
        "Remove article-heading prefix; preserve the factual claim."
    ),
    "E012": (
        "ACCEPT_TEXT_CLEANUP",
        "Separate chart heading/caption; independently verify survey figures."
    ),
    "E016": (
        "ACCEPT_TEXT_CLEANUP",
        "Insert missing space only; preserve both sentences."
    ),
}

selected = df[df["candidate_id"].isin(decisions)].copy()

selected["cleanup_decision"] = selected["candidate_id"].map(
    lambda cid: decisions[cid][0]
)
selected["decision_note"] = selected["candidate_id"].map(
    lambda cid: decisions[cid][1]
)

# These decisions apply only to text cleanup, not factual approval.
selected["factual_verification_status"] = "NOT_VERIFIED"
selected["review_status"] = "pending_review"
selected["supplier_specific_alert_allowed"] = False

assert set(selected["candidate_id"]) == set(decisions)
assert selected["proposed_evidence_sentence"].notna().all()
assert selected["review_status"].eq("pending_review").all()
assert not selected["supplier_specific_alert_allowed"].astype(bool).any()

selected.to_csv(output_path, index=False)

print("STEP 63 COMPLETE")
print("Decision file:", output_path)
print("Records:", len(selected))
print("\nCleanup decisions:")
print(selected[[
    "candidate_id",
    "cleanup_decision",
    "factual_verification_status",
    "review_status",
    "supplier_specific_alert_allowed"
]].to_string(index=False))

print("\nOriginal evidence files modified: No")
print("Production evidence promoted: No")

STEP 63 COMPLETE
Decision file: /content/ripplewatch_ai_v2/data/evidence_text_cleanup_decisions_v1.csv
Records: 3

Cleanup decisions:
candidate_id    cleanup_decision factual_verification_status  review_status  supplier_specific_alert_allowed
        E001 ACCEPT_TEXT_CLEANUP                NOT_VERIFIED pending_review                            False
        E012 ACCEPT_TEXT_CLEANUP                NOT_VERIFIED pending_review                            False
        E016 ACCEPT_TEXT_CLEANUP                NOT_VERIFIED pending_review                            False

Original evidence files modified: No
Production evidence promoted: No

In [ ]:

from pathlib import Path

app_path = Path("/content/ripplewatch_ai_v2/app.py")
lines = app_path.read_text(encoding="utf-8").splitlines()

for start, end in [(100, 160)]:
    print(f"--- app.py lines {start}-{min(end, len(lines))} ---")
    for i in range(start, min(end, len(lines)) + 1):
        print(f"{i}: {lines[i - 1]}")

print("\nSTEP 64 COMPLETE — READ-ONLY DASHBOARD REVIEW")

--- app.py lines 100-160 ---
100:     .value_counts()
101:     .sort_index()
102: )
103: if not score_counts.empty:
104:     st.bar_chart(score_counts)
105: else:
106:     st.info("No records match the selected filters.")
107:
108: st.subheader("Evidence records")
109:
110: display_columns = [
111:     "candidate_id",
112:     "verified_source_title",
113:     "verified_published_date",
114:     "signal_class",
115:     "industry_risk_score_v2",
116:     "score_reason_v2",
117:     "review_status_final",
118:     "risk_scope",
119:     "supplier_specific_alert_allowed"
120: ]
121:
122: st.dataframe(
123:     filtered[display_columns],
124:     use_container_width=True,
125:     hide_index=True
126: )
127:
128: st.subheader("Source details")
129: for _, row in filtered.iterrows():
130:     with st.expander(
131:         f"{row['candidate_id']} · {row['verified_source_title']}"
132:     ):
133:         st.write("Publication date:", (
134:             str(row["verified_published_date"].date())
135:             if pd.notna(row["verified_published_date"])
136:             else "Unknown"
137:         ))
138:
139:         article_url = (
140:             "https://www.supplychaindive.com/news/"
141:             "electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/"
142:         )
143:         st.link_button("Open original article", article_url)
144:
145:         st.write("Signal classification:", row["signal_class"])
146:         st.write("Preliminary score:", row["industry_risk_score_v2"])
147:         st.write("Scoring explanation:", row["score_reason_v2"])
148:         st.write("Review status:", row["review_status_final"])
149:         st.write("Risk scope:", row["risk_scope"])
150:         st.write(
151:             "Supplier-specific alert allowed:",
152:             bool(row["supplier_specific_alert_allowed"])
153:         )
154:
155: st.divider()
156: st.caption(
157:     "Prototype dashboard. Evidence requires manual verification. "
158:     "Industry-level reports must not be presented as confirmed risks "
159:     "to a named supplier or product."
160: )

STEP 64 COMPLETE — READ-ONLY DASHBOARD REVIEW

In [ ]:

from pathlib import Path
import pandas as pd

data_dir = Path("/content/ripplewatch_ai_v2/data")

summary = pd.read_csv(data_dir / "dashboard_evidence_summary.csv")
evidence = pd.read_csv(data_dir / "evidence.csv")
cleanup = pd.read_csv(data_dir / "evidence_text_cleanup_review_v1.csv")
decisions = pd.read_csv(
    data_dir / "evidence_text_cleanup_decisions_v1.csv"
)

print("1. UNIQUE ID CHECK")
for name, df, col in [
    ("Dashboard", summary, "candidate_id"),
    ("Evidence", evidence, "evidence_id"),
    ("Cleanup review", cleanup, "candidate_id"),
    ("Cleanup decisions", decisions, "candidate_id"),
]:
    print(f"{name}: {len(df)} rows; {df[col].nunique()} unique IDs")

print("\n2. DASHBOARD ↔ EVIDENCE MATCH")
dashboard_ids = set(summary["candidate_id"].astype(str))
evidence_ids = set(evidence["evidence_id"].astype(str))
print("Dashboard IDs missing from evidence:",
      sorted(dashboard_ids - evidence_ids))
print("Evidence IDs missing from dashboard:",
      sorted(evidence_ids - dashboard_ids))

print("\n3. CLEANUP DECISION MATCH")
decision_ids = set(decisions["candidate_id"].astype(str))
print("Decision IDs:", sorted(decision_ids))
print("All decisions have cleanup proposals:",
      decision_ids.issubset(set(cleanup["candidate_id"].astype(str))))
print("All decisions remain NOT_VERIFIED:",
      decisions["factual_verification_status"].eq("NOT_VERIFIED").all())

print("\nSTEP 65 COMPLETE — READ-ONLY MAPPING CHECK")

1. UNIQUE ID CHECK
Dashboard: 15 rows; 15 unique IDs
Evidence: 15 rows; 15 unique IDs
Cleanup review: 15 rows; 15 unique IDs
Cleanup decisions: 3 rows; 3 unique IDs

2. DASHBOARD ↔ EVIDENCE MATCH
Dashboard IDs missing from evidence: []
Evidence IDs missing from dashboard: []

3. CLEANUP DECISION MATCH
Decision IDs: ['E001', 'E012', 'E016']
All decisions have cleanup proposals: True
All decisions remain NOT_VERIFIED: True

STEP 65 COMPLETE — READ-ONLY MAPPING CHECK

In [ ]:

from pathlib import Path
from datetime import datetime
import shutil

app_path = Path("/content/ripplewatch_ai_v2/app.py")
assert app_path.exists(), f"App not found: {app_path}"

backup_path = app_path.with_name(
    f"app_backup_before_evidence_display_{datetime.now():%Y%m%d_%H%M%S}.py"
)
shutil.copy2(app_path, backup_path)

source = app_path.read_text(encoding="utf-8")

required_markers = [
    'st.subheader("Source details")',
    'st.write("Publication date:", (',
    'st.link_button("Open original article", article_url)',
]

print("Backup created:", backup_path)
print("Backup exists:", backup_path.exists())

print("\nINSERTION MARKER CHECK")
for marker in required_markers:
    print(f"{marker!r}: {marker in source}")

print("\nOriginal app unchanged by this cell.")
print("STEP 66 COMPLETE — BACKUP READY")

Backup created: /content/ripplewatch_ai_v2/app_backup_before_evidence_display_20261025_041109.py
Backup exists: True

INSERTION MARKER CHECK
'st.subheader("Source details")': True
'st.write("Publication date:", (': True
'st.link_button("Open original article", article_url)': True

Original app unchanged by this cell.
STEP 66 COMPLETE — BACKUP READY

In [ ]:

from pathlib import Path

app_path = Path("/content/ripplewatch_ai_v2/app.py")
source = app_path.read_text(encoding="utf-8")
lines = source.splitlines()

print("=== IMPORTS AND DATA LOADING ===")
for i, line in enumerate(lines[:100], start=1):
    print(f"{i:4}: {line}")

print("\n=== SOURCE DETAILS SECTION ===")
start = next(
    i for i, line in enumerate(lines)
    if 'st.subheader("Source details")' in line
)
for i in range(start, min(start + 65, len(lines))):
    print(f"{i+1:4}: {lines[i]}")

print("\nSTEP 67 COMPLETE — READ-ONLY CODE INSPECTION")

=== IMPORTS AND DATA LOADING ===
   1:
   2: from pathlib import Path
   3: import pandas as pd
   4: import streamlit as st
   5:
   6: PROJECT_DIR = Path("/content/ripplewatch_ai_v2")
   7: DATA_DIR = PROJECT_DIR / "data"
   8: DATA_FILE = DATA_DIR / "dashboard_evidence_summary.csv"
   9:
  10: st.set_page_config(
  11:     page_title="RippleWatch AI",
  12:     page_icon="🌊",
  13:     layout="wide"
  14: )
  15:
  16: st.title("🌊 RippleWatch AI")
  17: st.caption("Supply-chain risk intelligence | Industry-level signals")
  18:
  19: st.warning(
  20:     "Preliminary industry-level evidence only. "
  21:     "Scores are heuristic indicators, not calibrated probabilities. "
  22:     "No supplier-specific alerts are currently authorized."
  23: )
  24:
  25: if not DATA_FILE.exists():
  26:     st.error(f"Dashboard data file not found: {DATA_FILE}")
  27:     st.stop()
  28:
  29: df = pd.read_csv(DATA_FILE)
  30:
  31: required_columns = [
  32:     "candidate_id",
  33:     "verified_source_title",
  34:     "verified_published_date",
  35:     "signal_class",
  36:     "industry_risk_score_v2",
  37:     "score_reason_v2",
  38:     "review_status_final",
  39:     "risk_scope",
  40:     "supplier_specific_alert_allowed"
  41: ]
  42:
  43: missing = [col for col in required_columns if col not in df.columns]
  44: if missing:
  45:     st.error(f"Required columns are missing: {missing}")
  46:     st.stop()
  47:
  48: df["industry_risk_score_v2"] = pd.to_numeric(
  49:     df["industry_risk_score_v2"], errors="coerce"
  50: )
  51: df["verified_published_date"] = pd.to_datetime(
  52:     df["verified_published_date"], errors="coerce"
  53: )
  54:
  55: # Sidebar filters
  56: st.sidebar.header("Filters")
  57:
  58: signal_options = sorted(df["signal_class"].dropna().unique().tolist())
  59: selected_signals = st.sidebar.multiselect(
  60:     "Signal classification",
  61:     options=signal_options,
  62:     default=signal_options
  63: )
  64:
  65: min_score = st.sidebar.slider(
  66:     "Minimum preliminary score",
  67:     min_value=0,
  68:     max_value=100,
  69:     value=0,
  70:     step=5
  71: )
  72:
  73: filtered = df[
  74:     df["signal_class"].isin(selected_signals)
  75:     & (df["industry_risk_score_v2"] >= min_score)
  76: ].copy()
  77:
  78: # Summary metrics
  79: c1, c2, c3, c4 = st.columns(4)
  80: c1.metric("Evidence records", len(filtered))
  81: c2.metric(
  82:     "Reported industry signals",
  83:     int((filtered["signal_class"] == "reported_industry_signal").sum())
  84: )
  85: c3.metric(
  86:     "Needs manual review",
  87:     int((filtered["review_status_final"] == "manual_evidence_review").sum())
  88: )
  89: c4.metric(
  90:     "Supplier alerts allowed",
  91:     int(
  92:         filtered["supplier_specific_alert_allowed"]
  93:         .fillna(False).astype(bool).sum()
  94:     )
  95: )
  96:
  97: st.subheader("Industry signal score distribution")
  98: score_counts = (
  99:     filtered["industry_risk_score_v2"]
 100:     .value_counts()

=== SOURCE DETAILS SECTION ===
 128: st.subheader("Source details")
 129: for _, row in filtered.iterrows():
 130:     with st.expander(
 131:         f"{row['candidate_id']} · {row['verified_source_title']}"
 132:     ):
 133:         st.write("Publication date:", (
 134:             str(row["verified_published_date"].date())
 135:             if pd.notna(row["verified_published_date"])
 136:             else "Unknown"
 137:         ))
 138:
 139:         article_url = (
 140:             "https://www.supplychaindive.com/news/"
 141:             "electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/"
 142:         )
 143:         st.link_button("Open original article", article_url)
 144:
 145:         st.write("Signal classification:", row["signal_class"])
 146:         st.write("Preliminary score:", row["industry_risk_score_v2"])
 147:         st.write("Scoring explanation:", row["score_reason_v2"])
 148:         st.write("Review status:", row["review_status_final"])
 149:         st.write("Risk scope:", row["risk_scope"])
 150:         st.write(
 151:             "Supplier-specific alert allowed:",
 152:             bool(row["supplier_specific_alert_allowed"])
 153:         )
 154:
 155: st.divider()
 156: st.caption(
 157:     "Prototype dashboard. Evidence requires manual verification. "
 158:     "Industry-level reports must not be presented as confirmed risks "
 159:     "to a named supplier or product."
 160: )

STEP 67 COMPLETE — READ-ONLY CODE INSPECTION

In [ ]:

from pathlib import Path

app_path = Path("/content/ripplewatch_ai_v2/app.py")
source = app_path.read_text(encoding="utf-8")
lines = source.splitlines()

print("=== EXACT SOURCE DETAILS SECTION ===")
start = next(
    i for i, line in enumerate(lines)
    if 'st.subheader("Source details")' in line
)

for i in range(start, min(start + 40, len(lines))):
    print(f"{i+1}: {lines[i]!r}")

print("\n=== CURRENT APP CHECK ===")
print("App exists:", app_path.exists())
print("Source details section count:",
      source.count('st.subheader("Source details")'))
print("Evidence display code already present:",
      "Proposed cleaned evidence" in source)

print("\nSTEP 69 COMPLETE — READ-ONLY INSPECTION")

=== EXACT SOURCE DETAILS SECTION ===
128: 'st.subheader("Source details")'
129: 'for _, row in filtered.iterrows():'
130: '    with st.expander('
131: '        f"{row[\'candidate_id\']} · {row[\'verified_source_title\']}"'
132: '    ):'
133: '        st.write("Publication date:", ('
134: '            str(row["verified_published_date"].date())'
135: '            if pd.notna(row["verified_published_date"])'
136: '            else "Unknown"'
137: '        ))'
138: ''
139: '        article_url = ('
140: '            "https://www.supplychaindive.com/news/"'
141: '            "electronics-manufacturers-fret-over-extreme-heat-disruptions/830938/"'
142: '        )'
143: '        st.link_button("Open original article", article_url)'
144: ''
145: '        st.write("Signal classification:", row["signal_class"])'
146: '        st.write("Preliminary score:", row["industry_risk_score_v2"])'
147: '        st.write("Scoring explanation:", row["score_reason_v2"])'
148: '        st.write("Review status:", row["review_status_final"])'
149: '        st.write("Risk scope:", row["risk_scope"])'
150: '        st.write('
151: '            "Supplier-specific alert allowed:",'
152: '            bool(row["supplier_specific_alert_allowed"])'
153: '        )'
154: ''
155: 'st.divider()'
156: 'st.caption('
157: '    "Prototype dashboard. Evidence requires manual verification. "'
158: '    "Industry-level reports must not be presented as confirmed risks "'
159: '    "to a named supplier or product."'
160: ')'

=== CURRENT APP CHECK ===
App exists: True
Source details section count: 1
Evidence display code already present: False

STEP 69 COMPLETE — READ-ONLY INSPECTION

In [ ]:

from pathlib import Path
from datetime import datetime
import pandas as pd
import shutil

project_dir = Path("/content/ripplewatch_ai_v2")
data_dir = project_dir / "data"
app_path = project_dir / "app.py"

source = app_path.read_text(encoding="utf-8")

# Locate the exact boundaries.
start_marker = 'st.subheader("Source details")'
end_marker = "st.divider()"

assert source.count(start_marker) == 1, "Source details marker is ambiguous."
assert source.count(end_marker) >= 1, "Divider marker not found."

start = source.index(start_marker)
end = source.index(end_marker, start)
assert end > start, "Invalid section boundaries."

# Validate the evidence files and their schemas.
evidence_path = data_dir / "evidence.csv"
cleanup_path = data_dir / "evidence_text_cleanup_review_v1.csv"

evidence = pd.read_csv(evidence_path, dtype=str).fillna("")
cleanup = pd.read_csv(cleanup_path, dtype=str).fillna("")

assert {"evidence_id", "evidence_sentence"}.issubset(evidence.columns)
assert {"candidate_id", "proposed_evidence_sentence"}.issubset(cleanup.columns)
assert evidence["evidence_id"].is_unique
assert cleanup["candidate_id"].is_unique
assert set(cleanup["candidate_id"]).issubset(set(evidence["evidence_id"]))

new_section = '''st.subheader("Source details")

# Display extracted evidence and text-cleanup proposals without changing source CSVs.
evidence_display = pd.read_csv(DATA_DIR / "evidence.csv", dtype=str).fillna("")
cleanup_display = pd.read_csv(
    DATA_DIR / "evidence_text_cleanup_review_v1.csv", dtype=str
).fillna("")

evidence_by_id = evidence_display.set_index("evidence_id")["evidence_sentence"].to_dict()
cleanup_by_id = cleanup_display.set_index("candidate_id")["proposed_evidence_sentence"].to_dict()

for _, row in filtered.iterrows():
    candidate_id = str(row["candidate_id"])
    with st.expander(
        f"{candidate_id} · {row['verified_source_title']}"
    ):
        st.write("Publication date:", (
            str(row["verified_published_date"].date())
            if pd.notna(row["verified_published_date"])
            else "Unknown"
        ))

        article_url = str(row.get("source_url", "")).strip()
        if article_url.startswith(("https://", "http://")):
            st.link_button("Open original article", article_url)
        else:
            st.caption("Original article URL is unavailable in the dashboard data.")

        original_text = evidence_by_id.get(candidate_id, "").strip()
        proposed_text = cleanup_by_id.get(candidate_id, "").strip()

        if proposed_text:
            st.markdown("**Proposed cleaned evidence — NOT FACTUALLY VERIFIED**")
            st.write(proposed_text)
            st.caption(
                "Text cleanup only. This wording has not been factually verified."
            )
            if original_text:
                with st.expander("View original extracted text"):
                    st.write(original_text)
        elif original_text:
            st.markdown("**Extracted evidence — pending review**")
            st.write(original_text)
        else:
            st.warning("No evidence sentence found for this candidate ID.")

        st.write("Signal classification:", row["signal_class"])
        st.write("Preliminary score:", row["industry_risk_score_v2"])
        st.write("Scoring explanation:", row["score_reason_v2"])
        st.write("Review status:", row["review_status_final"])
        st.write("Risk scope:", row["risk_scope"])
        st.write(
            "Supplier-specific alert allowed:",
            bool(row["supplier_specific_alert_allowed"])
        )

'''

patched = source[:start] + new_section + source[end:]

# Preserve the current version before modifying app.py.
backup_path = project_dir / (
    f"app_backup_before_evidence_display_{datetime.now():%Y%m%d_%H%M%S}.py"
)
shutil.copy2(app_path, backup_path)

# Syntax-check before saving.
compile(patched, str(app_path), "exec")

app_path.write_text(patched, encoding="utf-8")

# Read-back validation.
saved = app_path.read_text(encoding="utf-8")
compile(saved, str(app_path), "exec")

assert saved.count(start_marker) == 1
assert "Proposed cleaned evidence — NOT FACTUALLY VERIFIED" in saved
assert "Supplier-specific alert allowed:" in saved

print("STEP 70 COMPLETE")
print("Backup:", backup_path)
print("Backup exists:", backup_path.exists())
print("Python syntax: PASS")
print("Evidence rows:", len(evidence))
print("Cleanup proposals:", len(cleanup))
print("Production evidence.csv modified: NO")
print("Risk scores/review statuses changed: NO")
print("Supplier alert permissions changed: NO")

STEP 70 COMPLETE
Backup: /content/ripplewatch_ai_v2/app_backup_before_evidence_display_20261025_041109.py
Backup exists: True
Python syntax: PASS
Evidence rows: 15
Cleanup proposals: 15
Production evidence.csv modified: NO
Risk scores/review statuses changed: NO
Supplier alert permissions changed: NO

In [ ]:

from pathlib import Path
import pandas as pd

project_dir = Path("/content/ripplewatch_ai_v2")
data_dir = project_dir / "data"
app_path = project_dir / "app.py"

app = app_path.read_text(encoding="utf-8")
summary = pd.read_csv(data_dir / "dashboard_evidence_summary.csv", dtype=str).fillna("")
evidence = pd.read_csv(data_dir / "evidence.csv", dtype=str).fillna("")
cleanup = pd.read_csv(
    data_dir / "evidence_text_cleanup_review_v1.csv", dtype=str
).fillna("")

print("1. APP CODE CHECK")
checks = {
    "Evidence CSV loaded": 'DATA_DIR / "evidence.csv"' in app,
    "Cleanup proposals loaded": 'evidence_text_cleanup_review_v1.csv' in app,
    "Unverified label present": "NOT FACTUALLY VERIFIED" in app,
    "Original extracted text available": "View original extracted text" in app,
    "Supplier alert status still displayed": "Supplier-specific alert allowed:" in app,
    "Original source URL used": 'row.get("source_url", "")' in app,
}
for name, passed in checks.items():
    print(f"{name}: {'PASS' if passed else 'FAIL'}")

print("\n2. ID MAPPING")
dashboard_ids = set(summary["candidate_id"].astype(str))
evidence_ids = set(evidence["evidence_id"].astype(str))
cleanup_ids = set(cleanup["candidate_id"].astype(str))

print("Dashboard records:", len(summary))
print("Evidence records:", len(evidence))
print("Cleanup proposal records:", len(cleanup))
print("Dashboard IDs missing from evidence:", sorted(dashboard_ids - evidence_ids))
print("Cleanup IDs absent from evidence:", sorted(cleanup_ids - evidence_ids))

print("\n3. SAFETY CHECK")
print("Supplier alerts enabled in evidence:",
      evidence["supplier_specific_alert_allowed"].astype(str).str.lower().isin(["true", "1"]).sum())
print("Review statuses in evidence:",
      evidence["review_status"].value_counts().to_dict())

print("\nSTEP 71 COMPLETE — VALIDATION ONLY")

1. APP CODE CHECK
Evidence CSV loaded: PASS
Cleanup proposals loaded: PASS
Unverified label present: PASS
Original extracted text available: PASS
Supplier alert status still displayed: PASS
Original source URL used: PASS

2. ID MAPPING
Dashboard records: 15
Evidence records: 15
Cleanup proposal records: 15
Dashboard IDs missing from evidence: []
Cleanup IDs absent from evidence: []

3. SAFETY CHECK
Supplier alerts enabled in evidence: 0
Review statuses in evidence: {'pending_review': 15}

STEP 71 COMPLETE — VALIDATION ONLY

In [ ]:

from pathlib import Path
import importlib.util
import subprocess
import sys
import time
import socket

project_dir = Path("/content/ripplewatch_ai_v2")
app_path = project_dir / "app.py"

assert app_path.exists(), "app.py not found"

if importlib.util.find_spec("streamlit") is None:
    print("Streamlit is not installed in this runtime.")
    print("Run this installation command in a separate cell:")
    print("%pip install streamlit")
else:
    # Check whether the default Streamlit port is already listening.
    sock = socket.socket()
    port_busy = sock.connect_ex(("127.0.0.1", 8501)) == 0
    sock.close()

    if port_busy:
        print("Port 8501 is already in use.")
        print("An app may already be running; no second process started.")
    else:
        log_path = project_dir / "streamlit_step72.log"
        log_file = open(log_path, "w", encoding="utf-8")

        process = subprocess.Popen(
            [
                sys.executable, "-m", "streamlit", "run", str(app_path),
                "--server.port", "8501",
                "--server.headless", "true",
            ],
            cwd=str(project_dir),
            stdout=log_file,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )

        time.sleep(3)
        print("Streamlit process ID:", process.pid)
        print("Log file:", log_path)
        print("Process running:", process.poll() is None)

        if process.poll() is not None:
            print("\nStartup log:")
            print(log_path.read_text(encoding="utf-8")[-5000:])

        print("\nIf the process is running, open the app using your Colab port preview.")
        print("STEP 72 COMPLETE — STARTUP ATTEMPT FINISHED")

Port 8501 is already in use.
An app may already be running; no second process started.

In [ ]:

import socket
import urllib.request
from pathlib import Path

app_path = Path("/content/ripplewatch_ai_v2/app.py")

print("1. PORT CHECK")
sock = socket.socket()
sock.settimeout(2)
port_open = sock.connect_ex(("127.0.0.1", 8501)) == 0
sock.close()
print("Port 8501 listening:", port_open)

print("\n2. STREAMLIT HEALTH CHECK")
try:
    request = urllib.request.Request(
        "http://127.0.0.1:8501/_stcore/health",
        headers={"User-Agent": "RippleWatch-Diagnostic"}
    )
    with urllib.request.urlopen(request, timeout=5) as response:
        print("HTTP status:", response.status)
        print("Response:", response.read(500).decode("utf-8", errors="replace"))
except Exception as exc:
    print("Health check failed:", repr(exc))

print("\n3. CURRENT APP PATCH")
source = app_path.read_text(encoding="utf-8")
print("Evidence display patch present:",
      "Proposed cleaned evidence — NOT FACTUALLY VERIFIED" in source)
print("Source details section present:",
      'st.subheader("Source details")' in source)

print("\nSTEP 73 COMPLETE — READ-ONLY DIAGNOSTIC")

1. PORT CHECK
Port 8501 listening: True

2. STREAMLIT HEALTH CHECK
HTTP status: 200
Response: ok

3. CURRENT APP PATCH
Evidence display patch present: True
Source details section present: True

STEP 73 COMPLETE — READ-ONLY DIAGNOSTIC

In [ ]:

from pathlib import Path
import urllib.request
import urllib.error

project_dir = Path("/content/ripplewatch_ai_v2")
app_path = project_dir / "app.py"

print("1. DASHBOARD PAGE")
try:
    req = urllib.request.Request("http://127.0.0.1:8501/")
    with urllib.request.urlopen(req, timeout=10) as response:
        html = response.read(12000).decode("utf-8", errors="replace")
        print("HTTP status:", response.status)
        print("Streamlit page detected:", "streamlit" in html.lower())
        print("Page response received:", len(html), "characters")
except Exception as exc:
    print("Page request failed:", repr(exc))

print("\n2. AVAILABLE STARTUP LOG")
log_path = project_dir / "streamlit_step72.log"
if log_path.exists():
    print(log_path.read_text(encoding="utf-8", errors="replace")[-3000:])
else:
    print("No Step 72 startup log exists; the server may be from an earlier run.")

print("\n3. PATCH CHECK")
source = app_path.read_text(encoding="utf-8")
print("Evidence display code present:",
      "Proposed cleaned evidence — NOT FACTUALLY VERIFIED" in source)
print("STEP 74 COMPLETE — SERVER CHECK")

1. DASHBOARD PAGE
HTTP status: 200
Streamlit page detected: True
Page response received: 6467 characters

2. AVAILABLE STARTUP LOG
No Step 72 startup log exists; the server may be from an earlier run.

3. PATCH CHECK
Evidence display code present: True
STEP 74 COMPLETE — SERVER CHECK